jbosstools/jbosstools-integration-tests

tests/org.jboss.tools.forge.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/test/suite/Forge2AllTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/JPASetupWizardTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/ProjectNewWizardTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/WizardTestBase.java

New util methods for getting Forge wizard and project creation.
Refactoring of existing forge2 tests to use util methods.
New forge persistence tests.

Forge2 new persistence tests and refactoring.

---

tests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/reddeer/test/CriteriaEditorTest.java
tests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/reddeer/test/HQLEditorTest.java
tests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/reddeer/test/JBossDatasourceTest.java
tests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/reddeer/test/JPAFacetTest.java
tests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/reddeer/test/MappingDiagramTest.java
tests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/reddeer/test/MappingFileTest.java
tests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/reddeer/test/MavenizedProjectTest.java
tests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/reddeer/test/PersistenceXMLFileTest.java
tests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/reddeer/test/RevengFileTest.java
tests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/reddeer/test/TablesFromJPAEntitiesGeneration.java

Conflicts:
tests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/reddeer/test/HQLEditorTest.java
tests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/reddeer/test/JBossDatasourceTest.java
tests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/reddeer/test/MappingDiagramTest.java

Final bunch of steps added into hibernate ui tests

---

plugins/org.jboss.tools.ui.bot.ext/src/org/jboss/tools/ui/bot/ext/SWTEclipseExt.java
tests/org.jboss.tools.portlet.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.portlet.ui.bot.test/launchers/AllTestsSuite_allConfigs.launch
tests/org.jboss.tools.portlet.ui.bot.test/launchers/AllTestsSuite_singleConfig.launch
tests/org.jboss.tools.portlet.ui.bot.test/launchers/prepare_workspace/portlets_prepare_workspace.launch
tests/org.jboss.tools.portlet.ui.bot.test/src/org/jboss/tools/portlet/ui/bot/test/template/HotDeploymentGateinTemplate.java
tests/org.jboss.tools.portlet.ui.bot.test/src/org/jboss/tools/portlet/ui/bot/test/template/RunPortletOnServerTemplate.java

Launchers were updated, few Waits were added and selecting alternate JRE in SWTBotExt was fixed.

Portlet tests cleanup.

---

tests/org.jboss.tools.mylyn.ui.bot.test/src/org/jboss/tools/mylyn/ui/bot/test/MylynTestLocalRepo.java
tests/org.jboss.tools.mylyn.ui.bot.test/src/org/jboss/tools/mylyn/ui/bot/test/MylynTestValidate.java

must all be unique in order for the integration with Polarion to be
successful

Changed the method names to be easier to identify - the method names

---

tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/webservice/BottomUpWSTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/webservice/TopDownWSTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/wsclient/WSClientTestTemplate.java

Workaround for the following eclispe bugs which cause test failures:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=428982 
and
https://bugs.eclipse.org/bugs/show_bug.cgi?id=468427

Implement workaround for eclipse issues

---

tests/org.jboss.tools.mylyn.ui.bot.test/pom.xml

Removing unsupported configuration fixes compiler configuration.

Fix missing class

---

tests/org.jboss.tools.jsf.ui.bot.test/src/org/jboss/tools/jsf/ui/bot/test/smoke/AbstractFacesConfigEditingTest.java

Fixes testManagedBean() to close Add managed Bean dialog properly branch 4.3.0.Beta1x

---

tests/org.jboss.tools.mylyn.ui.bot.test/pom.xml

Removing unsupported configuration fixes compiler configuration.

Fix missing class for 4.3.0.Beta1x branch

---

tests/org.jboss.tools.aerogear.ui.bot.test/src/org/jboss/tools/aerogear/ui/bot/test/AerogearBotTest.java

Construct context menus with regex instead of static strings. 

---

pom.xml

Hopefully this will be the last change.
Based on discussions in
https://github.com/jboss-reddeer/reddeer/pull/1115
and 
https://github.com/jboss-reddeer/reddeer/issues/1111
this should be final url that everybody agreed on.

Update RedDeer master repo url

---

plugins/org.jboss.tools.aerogear.reddeer/META-INF/MANIFEST.MF
plugins/org.jboss.tools.aerogear.reddeer/src/org/jboss/tools/aerogear/reddeer/ui/preferences/AndroidPreferencesPage.java
plugins/org.jboss.tools.aerogear.reddeer/src/org/jboss/tools/aerogear/reddeer/ui/preferences/FeedHenryPreferencesPage.java
plugins/org.jboss.tools.aerogear.reddeer/src/org/jboss/tools/aerogear/reddeer/ui/wizard/ImportCordovaApplicationWizard.java
tests/org.jboss.tools.aerogear.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.aerogear.ui.bot.test/src/org/jboss/tools/aerogear/ui/bot/test/FeedHenryAllBotTests.java
tests/org.jboss.tools.aerogear.ui.bot.test/src/org/jboss/tools/aerogear/ui/bot/test/FeedHenryBotTest.java
tests/org.jboss.tools.aerogear.ui.bot.test/src/org/jboss/tools/aerogear/ui/bot/test/rhmap/ImportFHApp.java

- New test for the import operation

Initial implementation of FeedHenry integration tests.

---

pom.xml
site/pom.xml
tests/org.jboss.tools.central.ui.bot.test/pom.xml

This should be merged into both master and Beta2x branches.

JBIDE-20394 add --del to deployment into mars/snapshots/updates; remove duplicate config inherited from parent pom

---

plugins/org.jboss.tools.forge.reddeer/META-INF/MANIFEST.MF
plugins/org.jboss.tools.forge.reddeer/src/org/jboss/tools/forge/reddeer/ui/wizard/ConnectionProfileWizardPage.java
tests/org.jboss.tools.forge.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.forge.ui.bot.test/pom.xml
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge/ui/bot/test/util/DatabaseUtils.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/test/suite/Forge2AllTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/ConnectionProfileWizardTest.java

Tests connection profile generation using sakila-h2 database.
Run with -Dtest.db={folder sakila db is located in} property to set the database up

Forge: Add Connection Profile Test

---

plugins/org.jboss.tools.jst.reddeer/META-INF/MANIFEST.MF
plugins/org.jboss.tools.jst.reddeer/src/org/jboss/tools/jst/reddeer/bower/ui/BowerInitDialog.java
tests/org.jboss.tools.jst.ui.bot.test/AllBowerTests.launch
tests/org.jboss.tools.jst.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.jst.ui.bot.test/src/org/jboss/tools/jst/ui/bot/test/AllBowerTests.java
tests/org.jboss.tools.jst.ui.bot.test/src/org/jboss/tools/jst/ui/bot/test/bower/BowerInitTest.java
tests/org.jboss.tools.jst.ui.bot.test/src/org/jboss/tools/jst/ui/bot/test/bower/BowerTestBase.java

New Tests:
* testBowerJsonCreated
* testBowerJsonOpenedInEditor
* testWizardRejectsWhenJsonFileExists
* testWizardRejectsEmptyBaseDir
* testWizardRejectsNonExistingDir
* testCanEditBowerConfigProperties

New Bower Init integration tests.

---

plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/ResourceExists.java
plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/OpenShiftProject.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3BotTests.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/TriggerBuildTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationFromTemplateTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/project/CreateNewProjectTest.java

OpenShift Trigger Build test added

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml

Fix reddeer config parameter (reddeer.config->rd.conifg) in quickstarts

---

plugins/org.jboss.tools.openshift.reddeer/META-INF/MANIFEST.MF
plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/ServerAdapterExists.java
plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/v2/DeleteUtils.java
plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/ServerAdapter.java
plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/v2/NewOpenShift2ApplicationWizard.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3BotTests.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/adapter/ID801SwitchProjectDeploymentTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/adapter/ID802ServerAdapterOverviewTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/adapter/ID803ServerAdapterHandlingTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/adapter/ID804CreateServerAdapterTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/advanced/ID904DeployApplicationWARArchiveTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/create/ID414CreateApplicationFromExistingProjectTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/handle/ID701ModifyAndRepublishApplicationTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/CreateServerAdapterTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ServerAdapterWizardHandlingTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/AbstractCreateApplicationTest.java

and added server adapter abstraction

Added OpenShift tests to create a new OS3 Server adapter

---

tests/org.jboss.tools.runtime.as.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.runtime.as.ui.bot.test/pom.xml
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/download/RuntimeDownloadTestBase.java

Also small bug in pom.xml was fixed.

Added required bundle instead of import package in runtime detection.

---

tests/org.jboss.tools.central.ui.bot.test/resources/server_properties/EAP62.xml
tests/org.jboss.tools.central.ui.bot.test/resources/server_properties/EAP63.xml
tests/org.jboss.tools.central.ui.bot.test/resources/server_properties/wildfly8.xml
tests/org.jboss.tools.runtime.as.ui.bot.test/resources/template/java6.xml
tests/org.jboss.tools.runtime.as.ui.bot.test/resources/template/java7.xml
tests/org.jboss.tools.runtime.as.ui.bot.test/resources/template/java8.xml

Requirements xmls switched to reddeer v1 in central and

---

plugins/org.jboss.ide.eclipse.as.reddeer/src/org/jboss/ide/eclipse/as/reddeer/server/family/FamilyEAP.java
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/detector/server/eap4/DetectEAP4.java
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/detector/server/eap51/DetectEAP51.java
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/detector/server/eap52/DetectEAP52.java
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/detector/server/eap60/DetectEAP60.java
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/detector/server/eap60x/DetectEAP60x.java
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/detector/server/eap61/DetectEAP61.java
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/detector/server/eap61x/DetectEAP61x.java
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/detector/server/eap62/DetectEAP62.java
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/detector/server/eap62x/DetectEAP62x.java
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/detector/server/eap63/DetectEAP63.java
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/detector/server/eap64/DetectEAP64.java
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/detector/server/eap70/DetectEAP70.java

"JBoss EAP" -> "Red Hat JBoss EAP"

Server renaming in runtime detection tests and Server requirement.

---

plugins/org.jboss.tools.arquillian.reddeer/src/org/jboss/tools/arquillian/ui/bot/reddeer/preferences/ArquillianPreferencePage.java
tests/org.jboss.tools.aerogear.ui.bot.test/src/org/jboss/tools/aerogear/ui/bot/test/AerogearBotTest.java
tests/org.jboss.tools.runtime.as.ui.bot.test/pom.xml
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/SmokeSuite.java

This PR is also to test "squash merge" feature of github.

Runtime detection smoke tests updated to use WFLY10

---

plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/core/ui/wizards/DockerConnectionWizard.java
tests/org.jboss.tools.docker.ui.bot.test/README
tests/org.jboss.tools.docker.ui.bot.test/pom.xml
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/DockerAllBotTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/SmokeSuite.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/ContainerTabTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/ImageTabTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/PullImageTest.java

Added SmokeSuite in Docker tests, minor fixes in Docker tests for Jenkins.

SmokeSuite in Docker tests, minor fixes for Jenkins

---

plugins/org.jboss.tools.maven.reddeer/src/org/jboss/tools/maven/reddeer/apt/ui/preferences/AnnotationProcessingSettingsPage.java
tests/org.jboss.tools.maven.ui.bot.test/pom.xml

Maven: Annotation processing dialog labels fix + POM minor fixes.

Maven: Annotation processing dialog labels fix + POM minor fixes

---

tests/pom.xml

Fix OSX path and profile after changing name from jbdevstudio to devstudio

---

tests/org.jboss.tools.runtime.as.ui.bot.test/pom.xml
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/ProjectTestsSuite.java
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/StableTestsSuite.java
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/detector/server/wildfly10web/DetectWildFly10Web.java
tests/org.jboss.tools.runtime.as.ui.bot.test/src/org/jboss/tools/runtime/as/ui/bot/test/download/ProductRuntimeDownload.java

EAP 7 added (other runtimes updated) and pom.xml maintanance in

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/AbstractImportQuickstartsTest.java
tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/QuickstartsReporter.java

POM updates:
- Updated EAP from Beta to Final
- Changed Quickstarts for JavaEE7 Smoke tests
Code Updates:
- Added more debug infos
- Added error handling for some quicstarts(cannot run on server)
- Added import artifacts for JavaEE7 quickstarts

Examples: changed URL in POM, added more debug information, fixes for specific quickstarts.

---

tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/RESTWSBotTests.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/annotation/AnnotationPropertiesTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/annotation/HTTPMethodAnnotationQuickFixTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/preferences/JBossWSPreferencesTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/FiltersInterceptorsSupportTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/NameBindingAnnotationSupportTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/PreMatchingAnnotationSupportTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/RESTfulTestBase.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/ValidatingRelatedRSElementsTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/explorer/RESTfulExplorerTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/param/BeanParamAnnotationSupportTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/param/MatrixParamAnnotationSupportTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/param/ParamConverterSupportTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/param/PathParamAnnotationSupportTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/param/QueryParamAnnotationSupportTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/validation/ApplicationValidationTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/validation/JaxRsValidatorTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/validation/RESTfulValidationTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/uiutils/PropertiesDialog.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/utils/ProjectHelper.java

and a workaround for upstream issue

REST tests fixes and updates

---

plugins/org.jboss.tools.openshift.reddeer/META-INF/MANIFEST.MF
plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftCommandLineToolsRequirement.java
plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/DatastoreOS3.java
plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/OpenShift3Connection.java
plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/page/EnvironmentVariableWizardPage.java
plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/page/ResourceLabelsWizardPage.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3BotTests.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3SmokeBotTests.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/BuilderImageApplicationWizardHandling.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/LabelsTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationFromTemplateTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationOnBuilderImageTest.java

- added test to create a new application based on builder image
- expanded builder image wizard tests
- refactoring for better code usage across wizards

OpenShift 3 new smoke tests and refactoring

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/AbstractImportQuickstartsTest.java
tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/QuickstartsReporter.java

Changes:
- Error handling improvements
- Added ignoring of folder starts with "."

Project examples - test improvements.

---

plugins/org.jboss.tools.docker.reddeer/META-INF/MANIFEST.MF
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/core/ui/wizards/DockerConnectionWizard.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/core/ui/wizards/RunADockerImagePageOneWizard.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/core/ui/wizards/RunADockerImagePageTwoWizard.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/core/ui/wizards/SearchDockerImagePageOneWizard.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/core/ui/wizards/SearchDockerImagePageTwoWizard.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/preferences/DockerMachinePreferencePage.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/preferences/DockerPreferencePage.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/preferences/LoggingPreferencePage.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/preferences/RegistryAccountsPreferencePage.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/ui/DockerExplorer.java
tests/org.jboss.tools.docker.ui.bot.test/launchers/DockerAllBotTest Socket.launch
tests/org.jboss.tools.docker.ui.bot.test/launchers/DockerAllBotTest TCP.launch
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/AbstractDockerBotTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/DockerAllBotTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/SearchDialogTest.java

Changes:
New test for search Docker Image Wizard
New launch configuration for socket connection
Renaming package
Changed timeouts for removing images/containers (fix for Central CI)

Docker - new tests

---

tests/pom.xml

starting devstudio on mac is currently broken, this PR fixes it

Fix starting devstudio on mac

---

tests/org.jboss.tools.freemarker.ui.bot.test/pom.xml

Adding PR check profile into Freemarker integration test pom.xml

---

tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge/ui/bot/console/test/CommandTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge/ui/bot/console/test/EntityTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge/ui/bot/console/test/InstallPluginTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge/ui/bot/console/test/PersistenceTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge/ui/bot/console/test/ProjectTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge/ui/bot/console/test/ScaffoldingTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge/ui/bot/test/suite/Forge1AllTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge/ui/bot/test/suite/ForgeConsoleTestBase.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge/ui/bot/test/util/DatabaseUtils.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge/ui/bot/test/util/ResourceUtils.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge/ui/bot/test/util/ScaffoldType.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/test/suite/Forge2AllTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/test/suite/SmokeSuite.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/CDISetupWizardTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/ConnectionProfileWizardTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/ConstraintSetupWizardTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/EJBSetupWizardTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/FacesSetupWizardTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/JPAEntitiesFromTablesTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/JPAEntityWizardTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/JPAFieldWizardTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/JPASetupWizardTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/ProjectNewWizardTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/RESTSetupWizardTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/ScaffoldSetupWizardTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/ScaffoldWizardTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/ServletSetupWizardTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/WizardTestBase.java

Changes:
- added copyright in all files
- added CDI test in Forge2AllTest suite
- Scaffold project functions moved in WizardTestBase (preparation for future Scaffold tests)

Forge - added Copyright/added test in Forge2AllTest

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml

New profile for project-examples PR check job

Added profile for project-examples PR Check

---

plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/core/ui/wizards/DockerConnectionWizard.java
tests/org.jboss.tools.docker.ui.bot.test/README
tests/org.jboss.tools.docker.ui.bot.test/launchers/DockerAllBotTest Search Connection.launch
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/AbstractDockerBotTest.java

Added support for searching connection to Docker(+ launch profile)

Added support for Docker Toolbox connection

---

plugins/org.jboss.tools.batch.reddeer/src/org/jboss/tools/batch/reddeer/editor/jobxml/JobXMLEditorDesignPage.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/AbstractBatchTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/design/DesignFlowElementsTestTemplate.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/features/AbstractFeatureBaseTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/features/CheckExistingReferenceTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/wizard/AbstractCreateArtifactTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/wizard/CreateJobXMLFileTest.java

Also, preparation of implicit initialization of test project to be run with each test class. Waits for upstream PR to be used properly (https://bugs.eclipse.org/bugs/show_bug.cgi?id=478634).

Changes to batch tests, repair of mistakes was done to CheckReference

---

tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/test/suite/Forge2AllTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/InstallAddonTest.java

Forge addon from catalog installation and remove.

New test for addon install from catalog

---

tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationOnBuilderImageTest.java

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

[JBIDE-23000] - Provide bot test for: Application based on builder images should have prefilled configuration

---

plugins/org.jboss.tools.batch.reddeer/src/org/jboss/tools/batch/reddeer/wizard/NewBatchArtifactWizardPage.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/AbstractBatchTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/features/AbstractFeatureBaseTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/wizard/AbstractCreateArtifactTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/wizard/CreateJobXMLFileTest.java

On windows, When opening Search View it does not get opened, added manual open call.
Sometimes, wizard window hangs, added conditional wait ShellWithTextIsAvailable.

Batch tests updates removing unstable behaviour

---

plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/core/ui/wizards/RunADockerImagePageTwoWizard.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/preferences/RegistryAccountsPreferencePage.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/ui/DockerContainersTab.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/ui/DockerExplorer.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/ui/DockerImageHierarchyTab.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/ui/DockerImagesTab.java
tests/org.jboss.tools.docker.ui.bot.test/README
tests/org.jboss.tools.docker.ui.bot.test/launchers/DockerAllBotTest Search Connection.launch
tests/org.jboss.tools.docker.ui.bot.test/launchers/DockerAllBotTest Socket.launch
tests/org.jboss.tools.docker.ui.bot.test/launchers/DockerAllBotTest TCP.launch
tests/org.jboss.tools.docker.ui.bot.test/pom.xml
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/AbstractDockerBotTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/DockerAllBotTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/ExposePortTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/LabelsTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/LinkContainersTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/VolumeMountTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/HierarchyViewTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/ImageTagTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/PullImageTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/PushImageTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/ContainerTabTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/DifferentRegistryTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/ImageTabTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/PerspectiveTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/PropertiesViewTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/SearchDialogTest.java

New tests and tests maintenance for new version of Docker Tooling

Fixes for new version of Docker Tooling + new tests

---

plugins/org.jboss.tools.arquillian.reddeer/src/org/jboss/tools/arquillian/ui/bot/reddeer/configurations/RunConfigurationsDialog.java
tests/org.jboss.tools.arquillian.ui.bot.test/pom.xml

To support pr-check profile - and to correct intermittent timeout issue

Jbide 23062 - Updates to arquillian bot tests

---

tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/InstallAddonTest.java

Added longer timeout and changed addon for InstallAddonTest

---

plugins/org.jboss.tools.cdk.reddeer/.gitignore
plugins/org.jboss.tools.cdk.reddeer/META-INF/MANIFEST.MF
plugins/org.jboss.tools.cdk.reddeer/build.properties
plugins/org.jboss.tools.cdk.reddeer/plugin.xml
plugins/org.jboss.tools.cdk.reddeer/pom.xml
plugins/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/Activator.java
plugins/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/condition/ServerHasState.java
plugins/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/preferences/OpenShift3SSLCertificatePreferencePage.java
plugins/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/ui/CDEServer.java
plugins/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/ui/CDEServersView.java
plugins/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/ui/wizard/CredentialsWizardPage.java
plugins/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/ui/wizard/NewServerContainerWizardPage.java
plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/OpenShiftExplorerView.java
plugins/pom.xml
site/category.xml
tests/org.jboss.tools.cdk.ui.bot.test/.gitignore
tests/org.jboss.tools.cdk.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.cdk.ui.bot.test/build.properties
tests/org.jboss.tools.cdk.ui.bot.test/launchers/CDKAllTestsSuite.launch
tests/org.jboss.tools.cdk.ui.bot.test/pom.xml
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/AllTestsSuite.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKDevstudioBaseTest.java
tests/pom.xml

That includes new integration tests:
- plugin org.jboss.tools.cdk.reddeer
- tests org.jboss.tools.cdk.ui.bot.test
Smoke tests cover setting up test environment (adding server adapter,accept SSL cert., etc.),
start, stop, restart server adapter, checking of docker and openshft connection.

[JBQA-13069] Added new CDK-Devstudio integration smoke test.

---

plugins/org.jboss.tools.batch.reddeer/src/org/jboss/tools/batch/reddeer/editor/design/BatchEditorTable.java
plugins/org.jboss.tools.batch.reddeer/src/org/jboss/tools/batch/reddeer/editor/jobxml/JobXMLEditorDesignPage.java
tests/org.jboss.tools.batch.ui.bot.test/launchers/BatchSuite.launch
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/AbstractBatchTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/AllTestsSuite.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/features/AbstractFeatureBaseTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/features/BatchExceptions.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/features/CheckExistingReferenceTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/features/RenameTest.java

Batch: Test of rename feature added. Work with tables in batch/design editor facilitated.
Changes in JobXMLEditorDesignPage helps to avoid problems on some Jenkins slaves.

Batch: Rename artefact test added

---

plugins/org.jboss.ide.eclipse.as.reddeer/src/org/jboss/ide/eclipse/as/reddeer/server/requirement/ServerRequirement.java

Label for EAP 7 has been changed in server wizard.

EAP 7 label fix

---

tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/before-handles-additionalParameters/WebContent/META-INF/MANIFEST.MF
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/before-handles-additionalParameters/WebContent/WEB-INF/beans.xml
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/before-handles-additionalParameters/pom.xml
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/before-handles-additionalParameters/src/test/StringProducer.java
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/before-handles-additionalParameters/src/test/Test.java
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/handles-additionalParameters/WebContent/META-INF/MANIFEST.MF
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/handles-additionalParameters/WebContent/WEB-INF/beans.xml
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/handles-additionalParameters/pom.xml
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/handles-additionalParameters/src/test/StringProducer.java
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/handles-additionalParameters/src/test/Test.java
tests/org.jboss.tools.deltaspike.ui.bot.test/src/org/jboss/tools/deltaspike/ui/bot/test/ExceptionHandlerMethodsTest.java

Deltaspike: Test of validation of additional parameters of exception handler method added.

Deltaspike: Test of validation of additional parameters of exception handler method

---

tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/configureProblemSeverity/WebContent/META-INF/MANIFEST.MF
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/configureProblemSeverity/WebContent/WEB-INF/beans.xml
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/configureProblemSeverity/pom.xml
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/configureProblemSeverity/src/exception/handler/Test.java
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/configureProblemSeverity/src/invalid/authorizer/CustomAuthorizer.java
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/configureProblemSeverity/src/invalid/authorizer/CustomSecurityBinding.java
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/configureProblemSeverity/src/invalid/handler/Test.java
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/configureProblemSeverity/src/umbiguous/authorizer/CustomAuthorizer.java
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/configureProblemSeverity/src/umbiguous/authorizer/CustomSecurityBinding.java
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/configureProblemSeverity/src/umbiguous/authorizer/SecuredBean.java
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/configureProblemSeverity/src/unresolved/authoriser/CustomAuthorizer.java
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/configureProblemSeverity/src/unresolved/authoriser/CustomSecurityBinding.java
tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/configureProblemSeverity/src/unresolved/authoriser/SecuredBean.java
tests/org.jboss.tools.deltaspike.ui.bot.test/src/org/jboss/tools/deltaspike/ui/bot/test/ValidationsInPreferenceTest.java
tests/org.jboss.tools.deltaspike.ui.bot.test/src/org/jboss/tools/deltaspike/ui/bot/test/condition/SpecificProblemExists.java

- ValidationsInPreferenceTest improved - changing of problem severity will be tested.
- SpecificProblemExists class allows to specify problem severity.

Deltaspike: ValidationsInPreferenceTest improved

---

tests/org.jboss.tools.aerogear.ui.bot.test/src/org/jboss/tools/aerogear/ui/bot/test/AerogearAllBotTests.java
tests/org.jboss.tools.aerogear.ui.bot.test/src/org/jboss/tools/aerogear/ui/bot/test/AerogearBotTest.java

bugs: 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=502146
https://bugs.eclipse.org/bugs/show_bug.cgi?id=506123

Fix failing aerogear tests - workaround for thym bugs

---

plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/preferences/DockerComposePreferencePage.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/ui/DockerExplorer.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/ui/RunDockerImageLaunchConfiguration.java
tests/org.jboss.tools.docker.ui.bot.test/launchers/DockerAllBotTest Search Connection.launch
tests/org.jboss.tools.docker.ui.bot.test/launchers/DockerAllBotTest Socket.launch
tests/org.jboss.tools.docker.ui.bot.test/launchers/DockerAllBotTest TCP.launch
tests/org.jboss.tools.docker.ui.bot.test/pom.xml
tests/org.jboss.tools.docker.ui.bot.test/resources/test-compose/Dockerfile
tests/org.jboss.tools.docker.ui.bot.test/resources/test-compose/app.py
tests/org.jboss.tools.docker.ui.bot.test/resources/test-compose/docker-compose.yml
tests/org.jboss.tools.docker.ui.bot.test/resources/test-compose/requirements.txt
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/DockerAllBotTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/ComposeTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/ContainerTabTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/DifferentRegistryTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/LaunchDockerImageTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/PropertiesViewTest.java

Docker Compose
Docker Launch Configuration

Docker Compose and Docker Launch Configuration tests

---

plugins/org.jboss.ide.eclipse.as.reddeer/META-INF/MANIFEST.MF
plugins/org.jboss.ide.eclipse.as.reddeer/src/org/jboss/ide/eclipse/as/reddeer/server/deploy/DeployOnServer.java

Deploy on server and check deployment refactoring

---

tests/org.jboss.tools.forge.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.forge.ui.bot.test/launchers/Forge2AllTest.launch
tests/org.jboss.tools.forge.ui.bot.test/pom.xml
tests/org.jboss.tools.forge.ui.bot.test/resources/servers/wildfly-10.xml
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/test/suite/Forge2AllTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/test/suite/SmokeSuite.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/ConnectionProfileWizardTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/DeployScaffoldDBTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/JPAEntitiesFromTablesTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/WizardTestBase.java

New test:
- create scaffold project with Forge and deploy it on running Wildfly server.

Forge Reveng Deploy Scaffold Test

---

plugins/org.jboss.tools.maven.reddeer/src/org/jboss/tools/maven/reddeer/wizards/ConfigureMavenRepositoriesWizard.java

Maven repository Windows specific fix

---

pom.xml

jbosstools_site_stream is now stream_jbt

JBIDE-23093 Adapt to variable changes in parent pom

---

plugins/org.jboss.ide.eclipse.as.reddeer/src/org/jboss/ide/eclipse/as/reddeer/server/deploy/DeployOnServer.java
tests/org.jboss.tools.docker.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/AbstractDockerBotTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/ExposePortTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/VolumeMountTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/ComposeTest.java

DeployOnServer - new methods/code refactoring
Docker - add kill pulling job after test finished,code refactoring

Docker - bug fix

---

plugins/org.jboss.tools.cdk.reddeer/META-INF/MANIFEST.MF
plugins/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/requirements/DisableSecureStorageRequirement.java
plugins/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/ui/CDEServer.java
plugins/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/ui/CDEServersView.java
plugins/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/ui/wizard/NewServerContainerWizardPage.java
tests/org.jboss.tools.cdk.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.cdk.ui.bot.test/launchers/CDKAllTestsSuite.launch
tests/org.jboss.tools.cdk.ui.bot.test/pom.xml
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKAllTestsSuite.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKDevstudioBaseTest.java

Adjusting timeouts for server adapter to start/stop. 
Added waiting conditions.

Requirement for disabling Secure Storage was added

---

tests/org.jboss.tools.arquillian.ui.bot.test/src/org/jboss/tools/arquillian/ui/bot/test/project/CreateArquillianProject.java

Reverts jbosstools/jbosstools-integration-tests#1674

Revert "Integration tests are failing dur to plugin lifecycle errors - set th…"

---

plugins/org.jboss.tools.aerogear.reddeer/src/org/jboss/tools/aerogear/reddeer/ui/properties/EnginePropertyPage.java
tests/org.jboss.tools.aerogear.ui.bot.test/src/org/jboss/tools/aerogear/ui/bot/test/AerogearBotTest.java
tests/org.jboss.tools.aerogear.ui.bot.test/src/org/jboss/tools/aerogear/ui/bot/test/app/MultiversionSupport.java

Fix failing Multiversion Test. Adds method getAvailableVersion that can skip nightly engines.

Fix failing Multiversion Test.

---

plugins/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/requirements/DisableSecureStorageRequirement.java
plugins/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/ui/CDEServer.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKDevstudioBaseTest.java

Print stack trace of catched exceptions

Update CDK test to reflect Docker plugin changes

---

plugins/org.jboss.tools.docker.reddeer/META-INF/MANIFEST.MF
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/condition/ImageIsDeployedCondition.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/ui/resources/DockerConnection.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/PushImageTest.java

* fixed DockerConnection¼getImage(name, tag) to inspect all tags
* fixed test to wait for push to be finished

[JBIDE-23640] DConnection#getImage by tag should inspect all tags

---

tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/project/CreateJSFProjectTest.java
tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/project/ExportImportWARTest.java
tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/project/RunJSFProjectTest.java

- Make tests independant
- Change time out
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

[JBIDE-23585] - Integration tests global refactoring: org.jboss.tools.jsf.ui.bot.test

---

plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/ui/DockerContainersTab.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/ui/DockerImagesTab.java
plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/ui/resources/DockerImage.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/AbstractDockerBotTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/DockerAllBotTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/ExposePortTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/LabelsTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/LinkContainersTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/PrivilegedModeTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/VariablesTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/VolumeMountTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/AbstractImageBotTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/DeleteImagesAfter.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/HierarchyViewTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/ImageTagTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/PullImageTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/ContainerTabTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/DifferentRegistryTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/ImageTabTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/LaunchDockerImageTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/PropertiesViewTest.java

Changes:
- Added class for deleting used images after all tests has been run
- Link Containers has been changed to use smaller images to speed up suite
- Unification on used images/images names

Docker test stabilization after last refactoring

---

plugins/org.jboss.tools.openshift.reddeer/META-INF/MANIFEST.MF
plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/AbstractOpenShiftApplicationWizard.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/OpenNewApplicationWizardTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationOnBuilderImageTest.java

CreateApplicationOnBuilderImageTest

Isolated OpenNewApplicationWizardTest and

---

plugins/org.jboss.ide.eclipse.as.reddeer/src/org/jboss/ide/eclipse/as/reddeer/server/deploy/DeployOnServer.java
plugins/org.jboss.tools.forge.reddeer/src/org/jboss/tools/forge/reddeer/condition/ForgeConsoleHasNoChange.java
plugins/org.jboss.tools.forge.reddeer/src/org/jboss/tools/forge/reddeer/condition/ProjectIsSelected.java
plugins/org.jboss.tools.forge.reddeer/src/org/jboss/tools/forge/reddeer/view/ForgeConsoleView.java
tests/org.jboss.tools.forge.ui.bot.test/launchers/Forge2AllTest.launch
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/test/suite/Forge2AllTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/DeployScaffoldDBTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/InstallAddonTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/LinkWorkspaceSelectionTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/WizardTestBase.java

Changes:
- Added better output in EvaluateBrowserPage method
- Added condition ForgeConsoleHasNoChange
- Added condition ProjectIsSelected
- Added tests for Link Workspace Selection to Forge Runtime

JBQA-6163 Link Workspace Selection to Forge Runtime implementation

---

tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/AbstractImageBotTest.java
tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/PullImageTest.java

Just added check for pulled images count and deleting images

[JBIDE-23655] Reworked test for pulling image without tag

---

plugins/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/ui/CDEServer.java
tests/org.jboss.tools.cdk.ui.bot.test/launchers/CDKAllTestsSuite.launch
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKDevstudioBaseTest.java

Refactor server adapter state change. Tests fails now on not showing OS SSL certificate.

CDK smoke test performance

---

plugins/org.jboss.tools.jst.reddeer/src/org/jboss/tools/jst/reddeer/web/ui/editor/jspeditor/JSPMultiPageEditor.java
plugins/org.jboss.tools.vpe.reddeer/src/org/jboss/tools/vpe/reddeer/condition/VPVEditorHasURL.java
plugins/org.jboss.tools.vpe.reddeer/src/org/jboss/tools/vpe/reddeer/preview/editor/VPVEditor.java
tests/org.jboss.tools.vpe.bot.test/pom.xml
tests/org.jboss.tools.vpe.bot.test/src/org/jboss/tools/vpe/bot/test/VPETestBase.java
tests/org.jboss.tools.vpe.bot.test/src/org/jboss/tools/vpe/bot/test/html5/HTML5EditorHighlight.java
tests/org.jboss.tools.vpe.bot.test/src/org/jboss/tools/vpe/bot/test/html5/jquery/MultiPageNavigation.java
tests/org.jboss.tools.vpe.bot.test/src/org/jboss/tools/vpe/bot/test/jsf/JSFEngineTest.java

JSF editor is not supported on OSX.

Wait for JQuery to be ready before executing any scripts.

---

tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/RemoveConnectionTest.java

- add connection requirement
- remove the connection recreation since requirements should take care of it

Isolate OS3 RemoveConnectionTest class

---

tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/integration/docker/DeployDockerImageTest.java

When JBIDE-23837 occurs again, screenshot with maximized
DockerExplorerView is captured and some more info is provided for easier
debugging.

Debug info added for JBIDE-23837.

---

tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/AbstractCreateApplicationTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationFromTemplateTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationOnBuilderImageTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/project/DeleteProjectTest.java

Fixes for special cases that may block the running tests + per class requirements.

OS3 application creation test fixes

---

tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/editor/AbstractFreemarkerTest.java
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/editor/FreemarkerDataModelTest.java
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/editor/FreemarkerRunDirectiveTest.java

Fixes test assert fails on windows 8

Add alternative test string for windows

---

tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/utils/ServersViewHelper.java

Duplicated PR to #1771 for branch jbosstools-4.4.x

There is no server in serverView fix

---

tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/annotation/AnnotationPropertiesTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/annotation/HTTPMethodAnnotationQuickFixTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/cxf/CxfWsClientTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/uiutils/PropertiesDialog.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/utils/DeploymentHelper.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/utils/ProjectHelper.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/utils/WebServiceClientHelper.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/webservice/WebServiceTestBase.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/wstester/WsTesterTest.java

Duplicated PR to #1755 for branch jbosstools-4.4.x

Webservices tests stabilizations

---

tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/CreateServerAdapterTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/PublishChangesTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ServerAdapterWizardHandlingTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/debug/NodeJSAppDebugTest.java

Do not merge before https://github.com/jbosstools/jbosstools-openshift/pull/1451 !!!

Fixed server adapter tests.

---

tests/org.jboss.tools.mylyn.ui.bot.test/pom.xml

Add JIRA connector repository in Mylyn tests POM

Add JIRA connector repository in Mylyn tests POM

---

tests/org.jboss.tools.forge.ui.bot.test/pom.xml
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/test/suite/Forge2AllTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/DeployScaffoldDBTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/InstallAddonTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/LinkWorkspaceSelectionTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/WizardTestBase.java

@psrna please review. Jenkins Build: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/forge.it.weekly

JBIDE-24136 Forge test fixes

---

tests/org.jboss.tools.forge.ui.bot.test/pom.xml

Rewritten Forge POM

---

plugins/org.jboss.tools.batch.reddeer/META-INF/MANIFEST.MF
plugins/org.jboss.tools.batch.reddeer/src/org/jboss/tools/batch/reddeer/editor/jobxml/JobXMLEditor.java
plugins/org.jboss.tools.batch.reddeer/src/org/jboss/tools/batch/reddeer/editor/jobxml/JobXMLEditorSourcePage.java
plugins/org.jboss.tools.batch.reddeer/src/org/jboss/tools/batch/reddeer/wizard/NewBatchArtifactWizardDialog.java
plugins/org.jboss.tools.batch.reddeer/src/org/jboss/tools/batch/reddeer/wizard/NewBatchArtifactWizardPage.java
plugins/org.jboss.tools.batch.reddeer/src/org/jboss/tools/batch/reddeer/wizard/NewJobXMLFileWizardDialog.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/AbstractBatchTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/AllTestsSuite.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/design/DesignBatchletStepElementTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/design/DesignFlowElementsTestTemplate.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/features/AbstractFeatureBaseTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/features/CheckExistingReferenceTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/features/RenameTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/wizard/AbstractCreateArtifactTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/wizard/CreateBatchXMLArtifactTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/wizard/CreateJobXMLFileTest.java
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/editor/AbstractFreemarkerTest.java
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/editor/FreeMarkerBaseEditorTest.java
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/editor/FreeMarkerCodeAssistTest.java
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/editor/FreemarkerDirectiveTest.java
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/editor/FreemarkerPreferencePageTest.java

Updates include Batch and Freemarker iTests

Updates to reflect reddeer 2.0 API changes

---

tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/project/ProjectPropertiesTest.java

Duplicated PR to #1814 for 4.4.x branch

openshift properties view test improvement JBIDE-23885

---

plugins/org.jboss.tools.batch.reddeer/src/org/jboss/tools/batch/reddeer/editor/jobxml/JobXMLEditorDesignPage.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/AllTestsSuite.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/jobxml/AbstractJobXMLReferenceTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/jobxml/AbstractJobXMLTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/jobxml/ValidateDesignRefAttributeTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/jobxml/ValidateSourceBatchPropertyTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/jobxml/ValidateSourceClassAttributeTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/jobxml/ValidateSourceElementLoopingTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/jobxml/ValidateSourceLevelReferenctingTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/jobxml/ValidateSourceRefAttributeTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/jobxml/ValidateSourceRestartAttributeTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/jobxml/ValidateSourceUniqueIDTest.java

Validation tests for ref attribute in job.xml file in design view tab

JBIDE-23729 - Validation tests for ref attribute in job.xml file

---

tests/pom.xml

Update devstudio.repository propery in pom.xml to use Oxygen update site.

Update devstudio.repository prop. to use Oxygen update site

---

plugins/org.jboss.tools.hibernate.reddeer/src/org/jboss/tools/hibernate/reddeer/condition/ConfigrationsAreLoaded.java
plugins/org.jboss.tools.hibernate.reddeer/src/org/jboss/tools/hibernate/reddeer/console/views/KnownConfigurationsView.java

Wait for hibernate configurations view to load

---

tests/org.jboss.tools.ws.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/facet/JAXRSFacetTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/integration/JAXRSToolingIntegrationTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/sample/SampleSoapServicesTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/uiutils/PropertiesDialog.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/utils/ProjectHelper.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/webservice/BottomUpWSTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/webservice/TopDownWSTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/webservice/WebServiceTestBase.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/webservice/eap/EAPFromJavaTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/webservice/eap/EAPFromWSDLTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/wsclient/WSClientTestTemplate.java

Jobs with stabilization branch are in playground:
https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jax-rs.stabilization/
https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/devstudio_playground/job/jax-ws.stabilization/

Stabilizations and refactoring

---

tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/StoreConnectionTest.java

Added test for JBIDE-19604 - improvement to new application wizard wrt

---

tests/org.jboss.tools.openshift.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.openshift.ui.bot.test/resources/eap70-basic-s2i-helloworld.json
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3SmokeBotTests.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/CreateServerAdapterTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/DebuggingEAPAppTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/DeleteResourceTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/DeploymentTest.java

DebuggingEAPAppTest stabilization as an side effect.

JBIDE-24543 - Slowly getting rid of AbstractCreateApplicationTest

---

tests/org.jboss.tools.examples.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/AbstractImportQuickstartsTest.java

Fixes almost all test failures...

JBIDE-24663 Added plugins for running tests in POM

---

tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKAbstractTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDK3ServerEditorTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDKServerEditorTest.java

if minishift location is invalid

Added new test for preventing saving of server editor 

---

tests/org.jboss.tools.openshift.ui.bot.test/resources/eap64-basic-s2i.json
tests/org.jboss.tools.openshift.ui.bot.test/resources/eap70-basic-s2i-helloworld.json
tests/org.jboss.tools.openshift.ui.bot.test/resources/os3projectWithResources/eap64-basic-s2i.json
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3SmokeBotTests.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/CreateServerAdapterTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/PublishChangesTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ServerAdapterWizardHandlingTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/EditResourcesTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/ImportApplicationTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/LogsTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/PortForwardingTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/TriggerBuildTest.java
tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationFromTemplateTest.java

Signed-off-by: rhopp <rhopp@redhat.com>

OS3 test fixes in 11.0.0.GA

---

tests/org.jboss.tools.cdk.ui.bot.test/launchers/CDKSmokeTestsSuite.launch
tests/org.jboss.tools.cdk.ui.bot.test/pom.xml
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDK3AllTestsSuite.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKAbstractTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKAllTestsSuite.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKSmokeTestsSuite.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK3ServerAdapterConnectionTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK3ServerAdapterRestartTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK3ServerAdapterStartTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterAbstractTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDK3ServerEditorTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDKServerEditorTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/CDK3ServerWizardTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/CDKServerWizardAbstractTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/CDKServerWizardTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/utils/CDKTestUtils.java

- CDK3IntegrationTest was refactored to be run as fast-smoke test
- CDKIntegrationTest class testing CDK 2.x was removed from suite
- CDK3ServerAdapterStart, CDK3ServerAdapterRestart and CDK3ServerAdapterConnection test classes were derived from CDK3Integration test class
- CDKSmokeTestsSuite launch file was added

Splitting test classes into smaller pieces

---

plugins/org.jboss.tools.perf/META-INF/MANIFEST.MF
plugins/org.jboss.tools.perf/src/org/jboss/tools/perf/test/core/reddeer/PerformanceRedDeerSuite.java
tests/org.jboss.tools.perf.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/PerfTestBase.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/PerfTestMavenBase.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/maven/validation/CDIMavenValidation.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/maven/validation/FullMavenValidationTest.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/maven/validation/HibernateMavenValidation.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/maven/validation/JAXRSMavenValidation.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/maven/validation/JPAValidationMavenTest.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/maven/validation/JSFMavenValidation.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/maven/validation/PortletMavenValidation.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/maven/validation/SeamMavenValidation.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/maven/validation/WTPMavenValidation.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/maven/wildfly/ImportMavenWildfly.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/validation/CDIValidation.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/validation/HibernateValidation.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/validation/JDTValidationTest.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/validation/JSTValidation.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/validation/NoValidationTest.java
tests/org.jboss.tools.perf.test/src/org/jboss/tools/perf/test/validation/WSTValidation.java

Update perf tests to use RedDeer2

---

tests/org.jboss.tools.freemarker.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/AllTestsSuite.java
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/SmokeTestsSuite.java
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/editor/AbstractFreemarkerTest.java
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/editor/FreeMarkerBaseEditorTest.java
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/editor/FreeMarkerCodeAssistTest.java
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/editor/FreemarkerDataModelTest.java
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/editor/FreemarkerDirectiveTest.java
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/editor/FreemarkerPreferencePage.java
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/editor/FreemarkerPreferencePageTest.java
tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/editor/FreemarkerRunDirectiveTest.java

Refactoring freemarker itests to use RedDeer 2.0

---

tests/org.jboss.tools.jsf.ui.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.jsf.ui.test/launchers/JSFAllTestsSuite.launch
tests/org.jboss.tools.jsf.ui.test/pom.xml
tests/org.jboss.tools.jsf.ui.test/resources/requirements.json
tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/AllTestsSuite.java
tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/SmokeTestsSuite.java
tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/project/CreateJSFProjectTest.java
tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/project/ExportImportWARTest.java
tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/project/RunJSFProjectTest.java
tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/requirement/DoNotUseVPERequirement.java
tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/utils/JSFTestUtils.java
tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/utils/ModuleIsInState.java

Refactoring jsf itest to use RedDeer 2.0

---

tests/org.jboss.tools.central.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.central.ui.bot.test/resources/Central Red Deer Test.launch
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/AllTestsSuite.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/ArchetypesTest.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/BasicTests.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/DnDTest.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/HTML5Parameterized.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/HTML5Test.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/SmokeSuite.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/internal/CentralBrowserIsLoading.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/prepareOffline/PrepareOfflineCommand.java

JBIDE-24945 Refactoring of Central integration tests for RedDeer2

---

tests/org.jboss.tools.eclipsecs.ui.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.eclipsecs.ui.test/launcher/CheckstyleTest.launch
tests/org.jboss.tools.eclipsecs.ui.test/launcher/CheckstyleUIPartsTest.launch
tests/org.jboss.tools.eclipsecs.ui.test/src/org/jboss/tools/eclipsecs/ui/test/AllSuite.java
tests/org.jboss.tools.eclipsecs.ui.test/src/org/jboss/tools/eclipsecs/ui/test/CheckStyleUIPartsTest.java
tests/org.jboss.tools.eclipsecs.ui.test/src/org/jboss/tools/eclipsecs/ui/test/CheckstyleTest.java
tests/org.jboss.tools.eclipsecs.ui.test/src/org/jboss/tools/eclipsecs/ui/test/view/GraphStatsView.java
tests/org.jboss.tools.eclipsecs.ui.test/src/org/jboss/tools/eclipsecs/ui/test/view/MarkerStatsView.java

Refactor eclipsecs tests to RedDeer2

---

tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/project/ArchetypesTest.java

JBIDE-24943 Small fix for maven integration tests

---

tests/org.jboss.tools.cdk.ui.bot.test/pom.xml

JBIDE-24970 Remove launchbar update site from pom.xml

---

tests/org.jboss.tools.batch.ui.bot.test/launchers/BatchAllTestsSuite.launch
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/AbstractBatchTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/design/DesignFlowElementsTestTemplate.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/jobxml/ValidateSourceBatchPropertyTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/wizard/CreateBatchXMLArtifactTest.java
tests/org.jboss.tools.cdk.ui.bot.test/launchers/CDKAllTestsSuite.launch
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDKServerEditorTest.java
tests/org.jboss.tools.freemarker.ui.bot.test/launcher/FreemarkerSmokeTestsSuite.launch

Removing integration tests bugs

---

plugins/org.jboss.tools.cdi.reddeer/src/org/jboss/tools/cdi/reddeer/uiutils/ValidationHelper.java
plugins/org.jboss.tools.livereload.reddeer/src/org/jboss/tools/livereload/reddeer/requirement/DockerWildflyRequirement.java
plugins/org.jboss.tools.livereload.reddeer/src/org/jboss/tools/livereload/reddeer/requirement/LivereloadServerRequirement.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDITestBase.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/validation/template/BeansXMLValidationQuickFixTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/wizard/template/CDIWebProjectWizardTemplate.java
tests/org.jboss.tools.deltaspike.ui.bot.test/src/org/jboss/tools/deltaspike/ui/bot/test/DeltaspikeTestBase.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/DeployScaffoldDBTest.java
tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/project/ExportImportWARTest.java
tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/project/RunJSFProjectTest.java
tests/org.jboss.tools.livereload.ui.bot.test/src/org/jboss/tools/livereload/ui/bot/test/LivereloadTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/apt/APTPropertiesPageTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/configurator/CDIConfiguratorTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/configurator/JAXRSConfiguratorTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/configurator/JSFConfiguratorTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/conversion/MavenConversionTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/project/JSFProjectTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/project/SeamProjectTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/WSTestBase.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/soap/SOAPTestBase.java

Adapt itests to changes in RedDeer 2 final.

---

tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/WSTestBase.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/soap/SOAPTestBase.java

Signed-off-by: Pavol Srna <psrna@redhat.com>

JBIDE-25105 Webservices: Refactoring for RedDeer 2.0.0.Final

---

tests/org.jboss.tools.cdk.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterAbstractTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDK3ServerEditorTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDKServerEditorTest.java

Adding cdk3 auto detection

---

tests/org.jboss.tools.cdk.ui.bot.test/resources/executable.sh
tests/org.jboss.tools.cdk.ui.bot.test/resources/non-executable
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKAbstractTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterAbstractTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDK3ServerEditorTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/CDK3ServerWizardTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/CDKServerWizardAbstractTest.java
tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/CDKServerWizardTest.java

Extend code to support mac platform

---

tests/org.jboss.tools.forge.ui.bot.test/build.properties
tests/org.jboss.tools.forge.ui.bot.test/launchers/Forge1AllTest.launch
tests/org.jboss.tools.forge.ui.bot.test/launchers/Forge2AllTest.launch
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/InstallAddonTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/LinkWorkspaceSelectionTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/WizardTestBase.java

JBIDE-25144 Forge ITests stabilization

---

tests/org.jboss.tools.ws.ui.bot.test/pom.xml
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/annotation/HTTPMethodAnnotationQuickFixTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/CreateJAXRSResourceTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/FiltersInterceptorsSupportTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/NameBindingAnnotationSupportTest.java

https://issues.jboss.org/browse/JBIDE-25150
https://issues.jboss.org/browse/JBIDE-25151
https://issues.jboss.org/browse/JBIDE-25153
https://issues.jboss.org/browse/JBIDE-25154
https://issues.jboss.org/browse/JBIDE-25155

JBIDE-25062 Fix for failing webservices REST integration tests

---

plugins/org.jboss.tools.browsersim.reddeer/src/org/jboss/tools/browsersim/reddeer/BrowserSimLauncher.java
plugins/org.jboss.tools.browsersim.rmi/src/org/jboss/tools/browsersim/rmi/BrowsersimWidgetLookup.java
tests/org.jboss.tools.livereload.ui.bot.test/pom.xml

Fix browsersim and livereload tests

---

tests/org.jboss.tools.jst.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.jst.ui.bot.test/src/org/jboss/tools/jst/ui/bot/test/json/ValidationTest.java

Signed-off-by: Pavol Srna <psrna@redhat.com>

JBIDE-25065 Fix failing jst integration tests.

---

plugins/org.jboss.tools.easymport.reddeer/src/org/jboss/tools/easymport/reddeer/wizard/SmartImportRootWizardPage.java
tests/org.jboss.tools.easymport.ui.bot.test/src/org/jboss/tools/easymport/ui/bot/test/EclipseJavaProjectTest.java
tests/org.jboss.tools.easymport.ui.bot.test/src/org/jboss/tools/easymport/ui/bot/test/FeatureProjectTest.java
tests/org.jboss.tools.easymport.ui.bot.test/src/org/jboss/tools/easymport/ui/bot/test/PlainEclipseProjectTest.java
tests/org.jboss.tools.easymport.ui.bot.test/src/org/jboss/tools/easymport/ui/bot/test/PlainJavaProjectTest.java
tests/org.jboss.tools.easymport.ui.bot.test/src/org/jboss/tools/easymport/ui/bot/test/ProjectTestTemplate.java

Use wizardpage as referenced composite where possible.

---

tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/NameBindingAnnotationSupportTest.java

Signed-off-by: Pavol Srna <psrna@redhat.com>

JBIDE-25259 Fix definingNameBindingAnnotationWithoutTargetAndRetentionTest

---

tests/org.jboss.tools.central.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/AllTestsSuite.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/InstallationDetailsTest.java

As commit name says.
But im not sure if the TODO in InstallationDetailsTest.java at line 78 is necessary, there may be some issues with future version change, g.e. if major version would be replaced with 2 numbers separated with dot - majorVersion1="11" to majorVersion2="12.0". Quickfix with OR to check both majorVersion1 and/or majorVersion2 in InstallationDetailsTest.java at lines 115-119.
Please not if there are any other links to validate.

JBDS-5064: Added validation of configuration details links

---

tests/org.jboss.tools.vpe.bot.test/src/org/jboss/tools/vpe/bot/test/html5/CreateHTML5Page.java

Check problems view instead of editor markers.

---

plugins/org.jboss.tools.browsersim.reddeer/src/org/jboss/tools/browsersim/reddeer/BrowserSimLauncher.java
plugins/org.jboss.tools.browsersim.rmi/src/org/jboss/tools/browsersim/browser/DeviceComposite.java
plugins/org.jboss.tools.browsersim.rmi/src/org/jboss/tools/browsersim/rmi/BrowserSimWithSkinMatcher.java
plugins/org.jboss.tools.browsersim.rmi/src/org/jboss/tools/browsersim/rmi/BrowsersimHandler.java
plugins/org.jboss.tools.browsersim.rmi/src/org/jboss/tools/browsersim/rmi/BrowsersimWidgetLookup.java
plugins/org.jboss.tools.browsersim.rmi/src/org/jboss/tools/browsersim/rmi/IBrowsersimHandler.java
plugins/org.jboss.tools.browsersim.rmi/src/org/jboss/tools/browsersim/rmi/SimUtil.java
tests/org.jboss.tools.browsersim.ui.bot.test/src/org/jboss/tools/browsersim/ui/bot/test/BrowsersimBaseTest.java

Wait without need for display.

---

plugins/org.jboss.tools.easymport.reddeer/META-INF/MANIFEST.MF
tests/org.jboss.tools.easymport.ui.bot.test/META-INF/MANIFEST.MF

JBIDE-25158 Minimize SmartImport test's dependencies in MANIFEST.MF
Signed-off-by: Lukáš Valach <lvalach@redhat.com>

JBIDE-25158 Minimize SmartImport test's dependencies in MANIFEST.MF

---

tests/org.jboss.tools.examples.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-11.json
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist-test-errors-regexes.json
tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/AbstractImportQuickstartsTest.java
tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/WildFlyImportQuickstartsTest.java

Updated WF quickstarts version

---

plugins/org.jboss.tools.aerogear.reddeer/src/org/jboss/tools/aerogear/reddeer/cordovasim/CordovaSimLauncher.java
plugins/org.jboss.tools.aerogear.reddeer/src/org/jboss/tools/aerogear/reddeer/thym/ui/engine/EngineDownloadDialog.java
plugins/org.jboss.tools.aerogear.reddeer/src/org/jboss/tools/aerogear/reddeer/thym/ui/properties/EnginePropertyPage.java
plugins/org.jboss.tools.aerogear.reddeer/src/org/jboss/tools/aerogear/reddeer/thym/ui/wizard/project/CordovaPluginWizard.java
plugins/org.jboss.tools.aerogear.reddeer/src/org/jboss/tools/aerogear/reddeer/thym/ui/wizard/project/EngineConfigurationPage.java
tests/org.jboss.tools.aerogear.ui.bot.test/pom.xml
tests/org.jboss.tools.aerogear.ui.bot.test/src/org/jboss/tools/aerogear/ui/bot/test/AerogearBotTest.java
tests/org.jboss.tools.aerogear.ui.bot.test/src/org/jboss/tools/aerogear/ui/bot/test/app/CreateHybridApplication.java
tests/org.jboss.tools.aerogear.ui.bot.test/src/org/jboss/tools/aerogear/ui/bot/test/app/MultiversionSupport.java

Signed-off-by: Pavol Srna <psrna@redhat.com>

JBIDE-25319 - fix failing aerogear.it job, failing tests due to recent UI/logic changes.

---

plugins/org.jboss.tools.cdi.reddeer/src/org/jboss/tools/cdi/reddeer/uiutils/EditorResourceHelper.java

REDDEER-1859 Remove workaround for REDDEER-1859, this issue seems to be fixed/I can't reproduce  it anymore.
Signed-off-by: Lukáš Valach <lvalach@redhat.com>

REDDEER-1859 Remove workaround for REDDEER-1859

---

tests/org.jboss.tools.maven.ui.bot.test/pom.xml
tests/org.jboss.tools.maven.ui.bot.test/resources/servers/wildfly-11.json

Fixed server version
Updated to wf11
[job run](https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/maven.itests/371/)
- green except for Mac.. working on it.

JBIDE-24976

---

tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/DeployScaffoldDBTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/LinkWorkspaceSelectionTest.java
tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/WizardTestBase.java

JBIDE-25815 Fixes for Forge ITests on Jenkins

---

tests/org.jboss.tools.browsersim.ui.bot.test/pom.xml
tests/org.jboss.tools.livereload.ui.bot.test/pom.xml

Install livereload and browsersim features to test environment

---

tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/AbstractBatchTest.java

JBIDE-23646 - Remove workaround for upstream bug

---

tests/org.jboss.tools.jsf.ui.test/pom.xml

Update URL to EAP servers in JSF test's pom.xml

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml

JBIDE-26142 Add repo for com.basistech.m2e.code.quality.checkstyle

---

tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDIAllBotTests.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDITestBase.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/template/BeansXMLDiscoveryModesTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/validation/template/CDIValidatorTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/wizard/cdi10/DynamicWebProjectWithCDITestCDI10.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/wizard/cdi10/EjbProjectWithCDITestCDI10.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/wizard/cdi10/UtilityProjectWithCDITestCDI10.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/wizard/template/CDIWebProjectWizardTemplate.java

Remove Java 1.7 compliance warning

---

tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/jobxml/AbstractJobXMLTest.java
tests/org.jboss.tools.jsf.ui.test/resources/requirements.json

Fixing javaee - EAP version 7.1 to 7.x

---

tests/org.jboss.tools.central.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.central.ui.bot.test/pom.xml
tests/org.jboss.tools.central.ui.bot.test/resources/Central Red Deer Test.launch
tests/org.jboss.tools.central.ui.bot.test/resources/eap-7.json
tests/org.jboss.tools.central.ui.bot.test/resources/settings.xml
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/ArchetypesTest.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/HTML5Parameterized.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/HTML5Test.java

JBIDE-26444 Add deploy on server in Central ITests

---

tests/org.jboss.tools.examples.ui.bot.test/README.md
tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-14.json

Updated WF from 11 to 14. Test report will be added soon. Please review @vprusa.

JBIDE-26439 - Update WF from 11 to 14

---

tests/org.jboss.tools.central.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.central.ui.bot.test/resources/blacklist-launcher-application-errors-regexes.json
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/AllTestsSuite.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/ArchetypesTest.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/BasicTests.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/LauncherApplicationTest.java

Add the Launcher Application tests. Needs my new class from jbosstools-central, where I created pull request a moment ago.

Add the Launcher Application tests.

---

tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/BasicTests.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/DnDTest.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/InstallationDetailsTest.java

JIRA: https://issues.jboss.org/browse/JBIDE-26551
Passed on Jenkins (both Java 8 and Java 11):

JBIDE-26551 - fixes the central testclass InstallationDetailsTest

---

tests/org.jboss.tools.batch.ui.bot.test/build.properties
tests/org.jboss.tools.batch.ui.bot.test/pom.xml
tests/org.jboss.tools.batch.ui.bot.test/resources/requirements.json
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/AbstractBatchTest.java

Update batch itests to pass jdk 11 runtime

---

tests/org.jboss.tools.maven.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/apt/APTPropertiesPageTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/configurator/CDIConfiguratorTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/configurator/JAXRSConfiguratorTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/configurator/JPAConfiguratorTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/configurator/JSFConfiguratorTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/configurator/PortletConfiguratorTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/configurator/SeamConfiguratorTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/conversion/MaterializeLibraryTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/conversion/MavenConversionTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/profile/MavenProfilesTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/project/ArchetypesTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/project/EARProjectTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/project/JSFProjectTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/project/SCMCheckoutProject.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/project/SeamProjectTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/repository/MavenRepositories.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/repository/RemoteRepositoriesPreferenceTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/sourcelookup/SourceLookupTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/ui/PerspectiveTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/ui/SeamPluginsTest.java

@jkopriva please review
Tested and passed on Jenkins:

JBDS-4738 Fix the APTPropertiesPageTest build path issue.

---

tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/ui/SeamPluginsTest.java

Fix the test in SeamPluginsTest testclass. Please review @jkopriva 
Jira: https://issues.jboss.org/browse/JBDS-4760
Tested on Jenkins:

JBDS-4760 Fix the test in SeamPluginsTest testclass

---

tests/org.jboss.tools.forge.ui.bot.test/pom.xml
tests/org.jboss.tools.forge.ui.bot.test/resources/servers/wildfly-15.json

JBIDE-26552 Update Forge ITests to use WildFly 15

---

tests/org.jboss.tools.livereload.ui.bot.test/pom.xml
tests/org.jboss.tools.livereload.ui.bot.test/resources/servers/wildfly.json

JBIDE-26553 Update LiveReload tests to use WildFly 15

---

tests/org.jboss.tools.jsf.ui.test/pom.xml
tests/org.jboss.tools.jsf.ui.test/resources/requirements.json

JSF itests using EAP 7.2 server

---

pom.xml

JBIDE-26579 Add Sonar profile

---

tests/org.jboss.tools.maven.ui.bot.test/pom.xml
tests/org.jboss.tools.maven.ui.bot.test/resources/servers/wildfly-16.json
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/AbstractMavenSWTBotTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/configurator/CDIConfiguratorTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/conversion/MavenConversionTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/utils/JavaVersionHelper.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/utils/ProjectHasNature.java

Update WildFly from version 11 to version 16 and make several necessary changes to fix tests.
Jenkins: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/maven.itests/688/
Jira: https://issues.jboss.org/browse/JBIDE-26557
@jkopriva please review

JBIDE-26557 Update WildFly from version 11 to version 16

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/eap-7.json
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/eap-blacklist
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/eap-blacklist-test-errors-regexes.json

- update EAP server to 7.2.1 and fix issues
Jenkins: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/examples.eap.it.weekly/650/
Jira: https://issues.jboss.org/browse/JBIDE-26645
@jkopriva please review

JBIDE-26645 - Fix the itests in job examples.eap.it.weekly

---

tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/wizard/cdi11/DynamicWebProjectWithCDITestCDI11.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/wizard/cdi11/EjbProjectWithCDITestCDI11.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/wizard/cdi11/UtilityProjectWithCDITestCDI11.java

Change default wf java(10) in dyn project to 1.8

---

plugins/org.jboss.tools.easymport.reddeer/META-INF/MANIFEST.MF
tests/org.jboss.tools.easymport.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.easymport.ui.bot.test/pom.xml

JBIDE-26667 Easyimport dependency fix

---

tests/org.jboss.tools.forge.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.forge.ui.bot.test/pom.xml
tests/org.jboss.tools.forge.ui.bot.test/resources/servers/wildfly-17.json

JBIDE-26674 Update Forge to use WF17

---

tests/org.jboss.tools.central.ui.bot.test/pom.xml
tests/org.jboss.tools.central.ui.bot.test/resources/blacklist-examples-errors-regexes.json
tests/org.jboss.tools.central.ui.bot.test/resources/eap-7.json
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/ArchetypesTest.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/BasicTests.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/DnDTest.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/HTML5Parameterized.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/InstallationDetailsTest.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/LauncherApplicationTest.java

JBIDE-24977 - fix the central.
Jenkins: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/central.itests/530/
please review @jkopriva

JBIDE-24977 - central.it.weekly fixes

---

tests/org.jboss.tools.maven.ui.bot.test/pom.xml
tests/org.jboss.tools.maven.ui.bot.test/resources/servers/wildfly-17.json
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/AbstractMavenSWTBotTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/configurator/JPAConfiguratorTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/conversion/MavenConversionTest.java

**Jenkins**: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/maven.itests/745/
**Jira**: https://issues.jboss.org/browse/JBIDE-26679

JBIDE-26679 - Update WF to version 17 in maven.itests

---

tests/org.jboss.tools.ws.ui.bot.test/pom.xml
tests/org.jboss.tools.ws.ui.bot.test/resources/config/requirements.json

JBIDE-27005 Update server in webservices itests

---

tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/AbstractMavenSWTBotTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/apt/APTPropertiesPageTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/configurator/AbstractConfiguratorsTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/conversion/MaterializeLibraryTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/conversion/MavenConversionTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/project/JSFProjectTest.java

**JBIDE-27006 - Fix several maven.itests tests (failing sporadically due to timeouts)**
**Jenkins:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/maven.itests/977/
**JIRA:** https://issues.redhat.com/browse/JBIDE-27006

JBIDE-27006 - Fix several maven.itests tests (failing sporadically due to timeouts)

---

tests/org.jboss.tools.maven.ui.bot.test/resources/servers/wildfly-10.json

Delete not used json in maven ITests

---

tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/project/JSFProjectTest.java

JBIDE-27146 - Fix the failing tests in JSFProjectTest testclass in maven.itests
**JIRA:** https://issues.redhat.com/browse/JBIDE-27146
**Jenkins:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/maven.itests/1154/

JBIDE-27146 - Fix the failing tests in JSFProjectTest testclass in maven.itests

---

tests/org.jboss.tools.ws.ui.bot.test/pom.xml
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/preferences/JBossWSPreferencesTest.java

Update ws itests to use wf-19

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/eap-7.json
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/eap-blacklist-test-errors-regexes.json

**Jira:** https://issues.redhat.com/browse/JBIDE-27275
**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-eap-itests/31/
please review @jkopriva @odockal

JBIDE-27275 - Update examples ITests to use EAP 7.3

---

plugins/org.jboss.tools.livereload.reddeer/META-INF/MANIFEST.MF
plugins/org.jboss.tools.livereload.reddeer/src/org/jboss/tools/livereload/reddeer/requirement/DockerWildflyRequirement.java

Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

JBIDE-27296: update docker client

---

plugins/org.jboss.tools.livereload.reddeer/META-INF/MANIFEST.MF

Fix Java version in manifest

---

tests/org.jboss.tools.livereload.ui.bot.test/pom.xml
tests/org.jboss.tools.livereload.ui.bot.test/resources/servers/wildfly.json

**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/livereload-itests/10/
**Jira:** https://issues.redhat.com/browse/JBIDE-27311

JBIDE-27311 - Update WildFly version in livereload.itests to version 20

---

tests/org.jboss.tools.cdi.bot.test/pom.xml
tests/org.jboss.tools.cdi.bot.test/resources/servers/requirements.json
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDITestBase.java

**Jira:** https://issues.redhat.com/browse/JBIDE-27312
**Jenkins:** 
- https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/DSL%20Jobs%20seed/job/Studio/job/Quality/job/Integration-tests/job/cdi12-itests/80/
- https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/DSL%20Jobs%20seed/job/Studio/job/Quality/job/Integration-tests/job/cdi20-itests/167/

JBIDE-27312 - Update WildFly version in cdi.itests to version 20

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist-test-errors-regexes.json
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly.json

**Jira:** https://issues.redhat.com/browse/JBIDE-27310
**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/22/

JBIDE-27310 - Update WildFly version in examples.itests to version 20

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/eap-xp-blacklist-test-errors-regexes.json
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/eap-xp-quickstarts-urls.json
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/eap-xp.json
tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/AbstractImportQuickstartsTest.java
tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/EAPXPImportQuickstartsTest.java

JBIDE-27270 EAP XP quickstarts automation

---

tests/org.jboss.tools.testng.ui.bot.test/.gitignore
tests/org.jboss.tools.testng.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.testng.ui.bot.test/build.properties
tests/org.jboss.tools.testng.ui.bot.test/pom.xml
tests/org.jboss.tools.testng.ui.bot.test/src/org/jboss/tools/testng/ui/bot/test/AbstractTestNGTest.java
tests/org.jboss.tools.testng.ui.bot.test/src/org/jboss/tools/testng/ui/bot/test/TestNGTest.java
tests/pom.xml

Signed-off-by: olkornii <olkornii@redhat.com>

JBIDE-27289: Create test for create and run TestNG class

---

tests/org.jboss.tools.ws.ui.bot.test/pom.xml
tests/org.jboss.tools.ws.ui.bot.test/resources/config/requirements.json
tests/org.jboss.tools.ws.ui.bot.test/resources/projects/wsPromptTestProject/src/wsPromptTestProject/MyApplication.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/cxf/CxfWsClientTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/preferences/JBossWSPreferencesTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/utils/ProjectHelper.java

- align deps with Jakarta EE 8

JBIDE-27048 Update wildfly 20, requirements

---

tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/configurator/AbstractConfiguratorsTest.java
tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/configurator/CDIConfiguratorTest.java

**Jira:** https://issues.redhat.com/browse/JBIDE-27273
**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/maven-itests/40/

JBIDE-27273 - Update maven configurator tests for the JBIDE-27145 issue

---

tests/org.jboss.tools.batch.ui.bot.test/pom.xml
tests/org.jboss.tools.cdi.bot.test/pom.xml
tests/org.jboss.tools.central.ui.bot.test/pom.xml
tests/org.jboss.tools.deltaspike.ui.bot.test/pom.xml

JBIDE-27291 Remove overwrite of JRE variables from ITests POMs(batch,

---

tests/org.jboss.tools.testng.ui.bot.test/src/org/jboss/tools/testng/ui/bot/test/AbstractTestNGTest.java
tests/org.jboss.tools.testng.ui.bot.test/src/org/jboss/tools/testng/ui/bot/test/TestNGTest.java

Signed-off-by: olkornii <olkornii@redhat.com>

JBIDE-27492: Reworked testNGtest. Removed Quick Fix use.

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml

Yellow build: https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-eap-xp-itests/5/
(same amount of failures)

Update EAP XP ITests

---

tests/org.jboss.tools.livereload.ui.bot.test/resources/servers/wildfly.json

Jenkins: https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/livereload-itests/41/
JIRA: https://issues.redhat.com/browse/JBIDE-27523

Update WildFly to version 21 in livereload.itests

---

tests/org.jboss.tools.maven.ui.bot.test/resources/servers/wildfly.json

Jenkins: https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/maven-itests/111/
Jira: https://issues.redhat.com/browse/JBIDE-27521

Update WildFly to version 21 in maven.itests

---

tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist-test-errors-regexes.json
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly.json

**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/74/
**Jira:** https://issues.redhat.com/browse/JBIDE-27524

Update WildFly to version 21 in examples.itests

---

tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/BasicTests.java

**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/central-itests/100/
**Jira:** https://issues.redhat.com/browse/JBIDE-27542

Extend the central itests to test the Quarkus link in central is present

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml

Update EAP XP to 2.0.0.GA-CR1

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml

Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

JBIDE-27639: fix master build when no profile specified.

---

tests/org.jboss.tools.livereload.ui.bot.test/pom.xml
tests/org.jboss.tools.livereload.ui.bot.test/resources/servers/wildfly.json

**Jira:** https://issues.redhat.com/browse/JBIDE-27568
**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/livereload-itests/58/

Update WildFly to version 22 in livereload.itests

---

tests/org.jboss.tools.easymport.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.testng.ui.bot.test/pom.xml

JBIDE-27645 Do not run ITests during build

---

tests/org.jboss.tools.maven.ui.bot.test/pom.xml
tests/org.jboss.tools.maven.ui.bot.test/resources/servers/wildfly.json

Jira: https://issues.redhat.com/browse/JBIDE-27567
Jenkins: https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/maven-itests/149/

Update WildFly to version 22 in maven.itests

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist-test-errors-regexes.json
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly.json

**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/109/
**Jira:** https://issues.redhat.com/browse/JBIDE-27566

Update WildFly to version 22 in examples.itests

---

tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/InstallationDetailsTest.java

**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/central-itests/136/
**Jira:** https://issues.redhat.com/browse/JBIDE-27723

Fix the failing InstallationDetailsTest (central itests)

---

tests/org.jboss.tools.maven.ui.bot.test/pom.xml
tests/org.jboss.tools.maven.ui.bot.test/resources/servers/wildfly.json

**Jira:** https://issues.redhat.com/browse/JBIDE-27686
**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/maven-itests/174/

Update WildFly to version 23 in maven.itests

---

tests/org.jboss.tools.livereload.ui.bot.test/pom.xml
tests/org.jboss.tools.livereload.ui.bot.test/resources/servers/wildfly.json

**Jira:** https://issues.redhat.com/browse/JBIDE-27685
**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/livereload-itests/69/

Update WildFly to version 23 in livereload.itests

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml

Fixed build: https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-eap-xp-itests/17/

JBIDE-27742 Update links for EAP XP tests

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist-test-errors-regexes.json
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly.json

Jenkins: https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/154/
Jira: https://issues.redhat.com/browse/JBIDE-27684
Please review @jkopriva (jira for the newly blacklisted quickstarts created - https://issues.redhat.com/browse/JBIDE-27772)

Update WildFly to version 23 in examples.itests

---

.github/workflows/build_test.yml

Introduce GitHub Actions PR Check workflow, fixes JBIDE-27768

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist-test-errors-regexes.json

**Jira:** https://issues.redhat.com/browse/JBIDE-27773
**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/159/

Update the checkstyle plugin version in wildfly.itests

---

tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/AbstractBatchTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/features/CheckExistingReferenceTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/features/RenameTest.java
tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/wizard/CreateBatchXMLArtifactTest.java

**Jira:** https://issues.redhat.com/browse/JBIDE-27785
**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/batch-itests/75/

Fix the failing batch itests due to some changes in project structure

---

tests/org.jboss.tools.deltaspike.ui.bot.test/src/org/jboss/tools/deltaspike/ui/bot/test/DeltaspikeTestBase.java
tests/org.jboss.tools.deltaspike.ui.bot.test/src/org/jboss/tools/deltaspike/ui/bot/test/PartialBeanTest.java

**Jira:** https://issues.redhat.com/browse/JBIDE-27791
**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/deltaspike-itests/129/

Fix the failing deltaspike itests due to some changes in project structure

---

plugins/org.jboss.tools.cdi.reddeer/src/org/jboss/tools/cdi/reddeer/CDIConstants.java
plugins/org.jboss.tools.cdi.reddeer/src/org/jboss/tools/cdi/reddeer/uiutils/BeansXMLHelper.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDITestBase.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/bean/template/BeanValidationQuickFixTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/decorator/template/DecoratorFromWebBeanTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/dialog/template/AllAssignableDialogTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/dialog/template/AssignableDialogFilterTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/named/teplate/NamedRefactoringTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/annotation/template/BeanParametersAnnotationTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/discovery/template/BeanDiscoveryInArchivesTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/template/BeansXMLDiscoveryModesTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/validation/template/BeansXMLValidationQuickFixTemplate.java

Please review @odockal 
**Jira:** https://issues.redhat.com/browse/JBIDE-27790
**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/cdi12-itests/187/

Fix the failing cdi itests due to some changes in project structure

---

tests/org.jboss.tools.testng.ui.bot.test/src/org/jboss/tools/testng/ui/bot/test/AbstractTestNGTest.java

Signed-off-by: Oleksii Korniienko <olkornii@redhat.com>

JBIDE-27828: Added selecting default tree before adding testNG library

---

tests/org.jboss.tools.ws.ui.bot.test/pom.xml
tests/org.jboss.tools.ws.ui.bot.test/resources/config/requirements.json
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/SOAPWSBotTests.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/SocketWSBotTests.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/WSTestBase.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/preferences/JBossWSPreferencesTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/CreateJAXRSApplicationTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/CreateJAXRSResourceTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/NameBindingAnnotationSupportTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/sample/SampleSoapServicesTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/soap/SOAPTestBase.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/utils/ProjectHelper.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/utils/ResourceHelper.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/webservice/BottomUpWSTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/webservice/TopDownWSTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/webservice/WebServiceTestBase.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/websocket/NameBindingTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/websocket/WebSocketHelper.java

Update and fix Webservices itests - REST based tests

---

tests/org.jboss.tools.ws.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.ws.ui.bot.test/pom.xml
tests/org.jboss.tools.ws.ui.bot.test/resources/config/requirements.json
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/RESTWSBotTests.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/SOAPWSBotTests.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/SocketWSBotTests.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/WSTestBase.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/preferences/JBossWSPreferencesTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/rest/CreateJAXRSApplicationTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/soap/SOAPTestBase.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/utils/ProjectHelper.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/websocket/WebSocketHelper.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/wsclient/WSClientTestTemplate.java

Fixes and workaround for sockets, rest and soap tests

---

tests/org.jboss.tools.livereload.ui.bot.test/pom.xml
tests/org.jboss.tools.livereload.ui.bot.test/resources/servers/wildfly.json

Please review @odockal @jkopriva 
Jenkins: https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/livereload-itests/92/
Jira: https://issues.redhat.com/browse/JBIDE-27824

JBIDE-27824 - Update WildFly to version 24 in livereload.itests

---

tests/org.jboss.tools.maven.ui.bot.test/pom.xml
tests/org.jboss.tools.maven.ui.bot.test/resources/servers/wildfly.json

Please review @jkopriva @odockal 
Jenkins: https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/maven-itests/227/
Jira: https://issues.redhat.com/browse/JBIDE-27825

JBIDE-27825 - Update WildFly to version 24 in maven.itests

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist-test-errors-regexes.json
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly.json

**Jenkins:** https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/209/
**Jira:** https://issues.redhat.com/browse/JBIDE-27826

JBIDE-27826 - Update WildFly to version 24 in examples.itests

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/eap-xp.json

Examples EAP XP 3.0.0.GA updates

---

plugins/org.jboss.tools.cdi.reddeer/src/org/jboss/tools/cdi/reddeer/uiutils/BeansXMLHelper.java
plugins/org.jboss.tools.cdi.reddeer/src/org/jboss/tools/cdi/reddeer/uiutils/EditorResourceHelper.java
tests/org.jboss.tools.cdi.bot.test/pom.xml
tests/org.jboss.tools.cdi.bot.test/resources/servers/requirements.json
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDI20SuiteTest.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDITestBase.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/decorator/template/DecoratorFromWebBeanTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/dialog/template/AllAssignableDialogTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/named/teplate/NamedComponentsSearchingTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/openon/template/BeanInjectOpenOnTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/openon/template/FindObserverEventTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/template/BeansXMLValidationTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/weld/template/WeldBuiltInContextsTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/wizard/template/CDIWebProjectWizardTemplate.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/wizard/template/ProjectWithCDITemplate.java

Updating CDI itests, updating wf, etc.

---

tests/org.jboss.tools.examples.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.examples.ui.bot.test/build.properties
tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/eap-7.json
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/eap-blacklist-test-errors-regexes.json
tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/AbstractImportQuickstartsTest.java

Update examples EAP 7.4

---

tests/pom.xml

Remove unsupported jvm options, fixes JBIDE-28180

---

pom.xml

Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

JBIDE-26888 : Replace http access to https

---

.github/workflows/build_test.yml

change master -> main

---

tests/org.jboss.tools.ws.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.ws.ui.bot.test/pom.xml
tests/org.jboss.tools.ws.ui.bot.test/resources/config/requirements.json
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/RESTWSBotTests.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/sample/SampleSoapServicesTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/utils/ServersViewHelper.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/webservice/BottomUpWSTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/webservice/TopDownWSTest.java
tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/wsclient/WSClientTestTemplate.java

fixing changes in webservices tooling

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml

Jenkins: https://studio-jenkins-csb-codeready.apps.ocp-c1.prod.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-eap-xp-itests/44/
Jira: https://issues.redhat.com/browse/JBIDE-28293

Update the link to download the EAP XP repository for JBEAPXP-3.0.0-7.4.3

---

tests/org.jboss.tools.examples.ui.bot.test/META-INF/MANIFEST.MF
tests/pom.xml

Update devstudio to jbt in tests/pom.xml

---

tests/org.jboss.tools.usage.ui.bot.test/src/org/jboss/tools/usage/ui/bot/test/AllTestsSuite.java
tests/org.jboss.tools.usage.ui.bot.test/src/org/jboss/tools/usage/ui/bot/test/ChangeUsagePreferenceTest.java

Signed-off-by: Tamara Babalova <tbabalov@redhat.com>

ChangeUsagePreferenceTest added

---

tests/org.jboss.tools.usage.ui.bot.test/META-INF/MANIFEST.MF

Signed-off-by: Tamara Babalova <tbabalov@redhat.com>

manifest fix

---

tests/org.jboss.tools.testng.ui.bot.test/src/org/jboss/tools/testng/ui/bot/test/AbstractTestNGTest.java
tests/org.jboss.tools.testng.ui.bot.test/src/org/jboss/tools/testng/ui/bot/test/TestNGTest.java

Signed-off-by: Oleksii Korniienko <olkornii@redhat.com>

Changed TabItem to CTabItem

---

tests/org.jboss.tools.usage.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.usage.ui.bot.test/pom.xml
tests/pom.xml

Usage pom fixes

---

pom.xml
tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist-test-errors-regexes.json
tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/AbstractImportQuickstartsTest.java

Jenkins: https://studio-jenkins-csb-codeready.apps.ocp-c1.prod.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/471/
Jira: https://issues.redhat.com/browse/JBIDE-28011

JBIDE-28011 - Update WildFly to version 26 in examples.itests

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist-test-errors-regexes.json

JIRA: https://issues.redhat.com/browse/JBIDE-28740
Jenkins: https://studio-jenkins-csb-codeready.apps.ocp-c1.prod.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/494/

JBIDE-28740 - Update WildFly to version 27 in examples.itests

---

tests/org.jboss.tools.central.ui.bot.test/META-INF/MANIFEST.MF
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/AllTestsSuite.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/BasicTests.java
tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/InstallationDetailsTest.java

- update tests
- remove JBDS based test

Include missing required bundle dependencies in central itests

---

tests/org.jboss.tools.cdi.bot.test/META-INF/MANIFEST.MF

Fixing CDI itets - adding required dependencies in tests

---

tests/org.jboss.tools.examples.ui.bot.test/pom.xml
tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly.json
tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/AbstractImportQuickstartsTest.java
tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/EAPImportQuickstartsTest.java
tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/WildFlyImportQuickstartsTest.java

Signed-off-by: Oleksii Korniienko <olkornii@redhat.com>

Fixed eap/wf-project-examples itests

---

tests/InstallDependencies.p2f

Replaced central dependencies "http" to "https" in InstallDependencies.p2f

Replaced central dependencies "http" to "https" 

---

tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDI20SmokeSuite.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDITestBase.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/annotation/cdi20/BeanParametersAnnotationTestCDI20.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/openon/cdi20/BeansXMLOpenOnTestCDI20.java
tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/openon/template/BeansXMLOpenOnTemplate.java

Added: 
BeanParametersAnnotationTestCDI20.class,
BeansXMLOpenOnTestCDI20.class

Added 2 more tests for cdi20 smoke suite
