jbosstools/jbosstools-integration-tests

site/pom.xml
The build was failing because we were using a very old version of repository-utils.
It's better to inherit the version from parent pom.
=> Remove old version of repository-utils from site/pom.xml

tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/WSTestBase.java, tests/org.jboss.tools.ws.ui.bot.test/src/org/jboss/tools/ws/ui/bot/test/wsclient/WSClientTestTemplate.java
Some ws tests check if console contains errors. This will cause them to fail if there is an error introduced by a previously run test. Console will now be cleared after each test to avoid this situation.
=> Clear console after each ws test

site/pom.xml
The site properties were set to 4.2 so the update site would say
4.2 on the html page which could be confusing.
=> Updated site properties to 4.3

pom.xml
Master branch will now point to version
4.3.0.Beta2-SNAPSHOT of parent pom.
=> Move to 4.3.0.Beta2-SNAPSHOT parent pom

pom.xml
Definition of jbosstools-integrationtests-site
in our root pom had master hardcoded at the end. It should use
the jbosstools_site_stream property.
=> Update integration tests repo to use site stream

tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/ProjectNewWizardTest.java, tests/org.jboss.tools.forge.ui.bot.test/src/org/jboss/tools/forge2/ui/bot/wizard/test/WizardTestBase.java
* Removes runtimes selection (there is only one default runtime - forge2 )
* Fixies label changes in new project wizard
=> Fix for JBT 4.3.0.Beta1 changes for forge.

pom.xml
Vlado or Jirka pointed out today that RedDeer is not on mars yet,
so I changed the jenkins job to publish to luna in the url.
=> Update RedDeer master url: mars -> luna

pom.xml
Before tagging our tests for JBoss Tools 4.3.0.Beta1,
we want to set the RedDeer url to one that doesn't change.
=> Set root pom to use RedDeer 0.8.0.M1

pom.xml
The url has changed, so updating accordingly.
The one that we have in the pom now is now 404.
=> Set root pom to use RedDeer 0.8.0.M1 - fix

pom.xml
For Beta2, the tests will always use RedDeer 0.8.0
in all places where master was used.
I could have made sure that all tests are set to use
stable url and changed the stable url to 0.8.0,
but this approach seems easier and fool-proof.
=> Hardwired integration tests to use RedDeer 0.8.0

pom.xml
For JBDS 9.0.0.GA / JBoss Tools 4.3.0.Final, we need
to point to a RedDeer URL that doesn't move. I created
a milestone from RedDeer master and we will use it.
=> Change RedDeer master url to a static milestone

pom.xml
JBIDE-21621 added RedDeer to 4.60.0.Alpha1-SNAPSHOT TP,
so from JBoss Tools 4.4.0.Alpha1 onward, we can rely on that
and do not need our own repo definition anymore. When we need to
update RedDeer in TP, we request that in a JIRA.
=> JBIDE-21621 Remove RedDeer repo definition as it is in TP now

tests/org.jboss.tools.central.ui.bot.test/src/org/jboss/tools/central/test/ui/reddeer/DnDTest.java
I saw this failing on Central CI slaves. This should prevent it from happening.
=> Wait for installation timeout extended in DnD tests.

tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/AbstractBatchTest.java, tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/design/DesignFlowElementsTestTemplate.java, tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/wizard/AbstractCreateArtifactTest.java, tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/wizard/CreateJobXMLFileTest.java
To make each test class independent.
Due to upstream bug that causes looping of workspace building,
it was not possible to import/remove project for each test class via UI.
Eclipse API is used to delete project and thus, bug is avoided.
=> Remove dependency on first test class

tests/pom.xml
This will solve the problem of needing integration-tests repo
to run a single test. Now you can run a single test using the root pom.
This way you will have all the bundles in the reactor.
=> Add profile to run a single test bundle in tests/pom.xml

tests/org.jboss.tools.easymport.ui.bot.test/pom.xml
A reference of swtbot.test.skip
was left out in easymport test pom.
We don't use this property anymore.
In the near future, we should also remove skipTests definitions from the poms - all tests should run by default. But that will come later.
=> JBIDE-23624 Remove swtbot.test.skip

plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/ConsoleHasSomeText.java, plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftCommandLineToolsRequirement.java, plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java, plugins/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/v3/TemplatesCreator.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/handle/ID705TailFilesTest.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/CreateServerAdapterTest.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/PublishChangesTest.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ServerAdapterWizardHandlingTest.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/DeleteResourceTest.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/DeployEclipseProjectTest.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/ImportApplicationTest.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/LogsTest.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/PortForwardingTest.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/BuilderImageApplicationWizardHandlingTest.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/AbstractCreateApplicationTest.java
OpenShift 3 Smoke suite should be almost OK. Publish Test will need more love, but for now it is better.
What has been done:
- oc version upgraded
- fixed issue of ConsoleHasText if no console is available/there is no styled  text in console
- updated builder image, started to use 1.3 instead of 1.2
- server adapter test stabilized by killing refreshing server adapter info
- revamped port wizard page in builder image wizard
- logged tests revamped, removed 2 out of dated
=> OpenShift 3 fixes

plugins/org.jboss.ide.eclipse.as.reddeer/src/org/jboss/ide/eclipse/as/reddeer/server/requirement/ServerRequirementConfig.java
When running tests in runtime workbench, doesn't make much sense to force people to go override the jboss-as71.xml file to get tests working. Seems if maven hasn't replaced the flag, the tests will get ${some.var} anyway, so the test framework can check for that and then check sysprop and see if a value has been provided there.
=> Allow user to set config file properties via sysprop

plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/core/ui/wizards/NewDockerConnectionPage.java, plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/ui/DockerExplorerView.java, tests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKDevstudioBaseTest.java, tests/org.jboss.tools.docker.ui.bot.test/META-INF/MANIFEST.MF, tests/org.jboss.tools.docker.ui.bot.test/README, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/AbstractDockerBotTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/connection/AddConnectionTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/DockerContainerTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/ExposePortTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/LabelsTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/LinkContainersTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/PrivilegedModeTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/VariablesTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/VolumeMountTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/BuildImageTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/HierarchyViewTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/ImageTagTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/PullImageTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/PushImageTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/ComposeTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/ContainerTabTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/DifferentRegistryTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/ImageTabTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/LaunchDockerImageTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/PerspectiveTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/PropertiesViewTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/SearchDialogTest.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/integration/docker/DeployDockerImageTest.java
Connections in the Docker explorer must be unique in name and unique in
host. AddConnectionTest thus can fail if there already is a connection
using the same host with a different name.
This should be fixed by looking up connections by their host.
=> [JBIDE-23629] fixed AddConnectionTest to lookup conns by host

tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/conversion/MavenConversionTest.java
For example, `sun-jaxws:jsr181-api:jar:2.1.1` couldn't have been resolved as it doesn't exist in jboss-public-repository and that's why `MavenConversionTest.keepDependenciesAfterConversion` test was failing with `WaitTimeoutExpiredException` in `checkProblemsAndResolve()` method
=> jbide-23587: add maven2 repository to resolve all dependencies

plugins/org.jboss.tools.batch.reddeer/src/org/jboss/tools/batch/reddeer/wizard/NewBatchArtifactWizardPage.java, tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/AbstractBatchTest.java, tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/features/AbstractFeatureBaseTest.java, tests/org.jboss.tools.batch.ui.bot.test/src/org/jboss/tools/batch/ui/bot/test/editor/features/RenameTest.java
- caused test failures on windows 10
- will be refactored after upstream patch is released [jira](https://issues.jboss.org/browse/JBIDE-23646)
Refactoring to renaming test
Added additional setting of focus to Add property shell in batch artifact wizard
- shell was losing focus on rhel
=> Workaround of safe deleting of project with reddeer direct api

plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/condition/ContainerIsDeployedCondition.java, plugins/org.jboss.tools.docker.reddeer/src/org/jboss/tools/docker/reddeer/ui/resources/DockerConnection.java, tests/org.jboss.tools.docker.ui.bot.test/META-INF/MANIFEST.MF, tests/org.jboss.tools.docker.ui.bot.test/README, tests/org.jboss.tools.docker.ui.bot.test/resources/test-build/Dockerfile, tests/org.jboss.tools.docker.ui.bot.test/resources/test-volumes/index.html, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/AbstractDockerBotTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/DockerContainerTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/ExposePortTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/LabelsTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/LinkContainersTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/PrivilegedModeTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/VariablesTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/container/VolumeMountTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/AbstractImageBotTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/BuildImageTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/HierarchyViewTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/ImageTagTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/PullImageTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/PushImageTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/ComposeTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/ContainerTabTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/DifferentRegistryTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/ImageTabTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/LaunchDockerImageTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/PropertiesViewTest.java, tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/ui/SearchDialogTest.java
the following changes lead to a very much shorter runtime of the whole suite:
* used smaller docker images to speed up the suite (BuildImageTest,
PullImageTest, ExposedPortTest, ContainerTabTest, PropertiesViewTest,
LaunchDockerImageTest, DockerContainerTest, DifferentRegistryTest,
VolumeMountTest)
* pulling instead of building in HierarchyViewTest
* fixed DockerConnectio#getImageNames and #deployedImagesCount so that
specific image versions can be asserted
* introduced AbstractImageBotTest as base class for all tests that deal
with images (build, push, pull, etc.)
* added AbstractImageBotTest#deleteContainerIfExists to delete
containers from previous test runs
* corrected static fields in test to be consistently static & final
=> [JBIDE-23633] use small docker images to speed up the suite

tests/org.jboss.tools.examples.ui.bot.test/pom.xml, tests/org.jboss.tools.examples.ui.bot.test/resources/servers/eap-blacklist, tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist, tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/AbstractImportQuickstartsTest.java, tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/EAPImportQuickstartsTest.java, tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/WildFlyImportQuickstartsTest.java
Changes:
- Added blacklist file for wildfly and EAP examples, which are not supported in DevStudio
- Deploy on server is not activated by default - now is tested only import in DevStudio, leaving support for deploying on server for future testing purporses
=> Examples - Added blacklist file for non supported quickstarts in DevStudio

tests/org.jboss.tools.openshift.ui.bot.test/resources/os3projectWithResources/.project, tests/org.jboss.tools.openshift.ui.bot.test/resources/os3projectWithResources/eap64-basic-s2i.json, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationFromTemplateTest.java
CreateApplicationFromTemplateTest should now run in Jenkins. New simple
project is used instead of org.jboss.tools.openshift.ui.bot.test, which
was used before (.project file was not present)
=> Use simple project in CreateApplicationFromTemplateTest

tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/NewApplicationWizardHandlingTest.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/OpenNewApplicationWizardWithNoProjectTest.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationFromTemplateTest.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/CreateNewConnectionTest.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/StoreConnectionTest.java, tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/project/LinkToCreateNewProjectTest.java
* LOCAL_TEMPLATE changed to CUSTOM_TEMPLATE
* ITests are now using eap70 instead of eap64 templates
* StoreConnectionTest now forces usage of UI Prompt
=> Reflexing bug JBIDE-24492 in ITests & minor fixes.

tests/org.jboss.tools.examples.ui.bot.test/pom.xml, tests/org.jboss.tools.examples.ui.bot.test/resources/servers/eap-7.xml, tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/EAPImportQuickstartsTest.java, tests/org.jboss.tools.jsf.ui.test/resources/EAP70.xml, tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/project/CreateJSFProjectTest.java, tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/project/ExportImportWARTest.java, tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/project/RunJSFProjectTest.java, tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/utils/JSFTestUtils.java
Updates made to reflect deprecated EAP7x server type requirement. See [PR](https://github.com/jbosstools/jbosstools-server/pull/519). Added some stabilization efforts.
=> Jsf stabilization

plugins/org.jboss.tools.cdi.reddeer/META-INF/MANIFEST.MF, plugins/org.jboss.tools.easymport.reddeer/META-INF/MANIFEST.MF
JBIDE-24532 CDI and EasyImport plugins will use RedDeer 1.2.2
=> JBIDE-24532 CDI and EasyImport plugins will use RedDeer 1.2.2

tests/org.jboss.tools.easymport.ui.bot.test/pom.xml, tests/org.jboss.tools.easymport.ui.bot.test/src/org/jboss/tools/easymport/ui/bot/test/ProjectTestTemplate.java
Add possibility to ignore some errors in Error View. Test can be started with parameter like this: 
-Dignored.errors.regexp="Some error \.\*|Another error".
Also added Abstract wait before cleaning of Error View at start up because some of irelevant errors can appear after a while.
Signed-off-by: Lukáš Valach <lvalach@redhat.com>
=> JBIDE-24978 Stabilize SmartImport tests.

tests/org.jboss.tools.cdi.bot.test/pom.xml, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDI10SmokeSuite.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDI11SmokeSuite.java
JBIDE-24900 Split CDI 10/11 smoke tests to separated suites.
Signed-off-by: Lukáš Valach <lvalach@redhat.com>
=> JBIDE-24900 Split CDI 10/11 smoke tests to separated suites.

tests/org.jboss.tools.examples.ui.bot.test/README.md, tests/org.jboss.tools.examples.ui.bot.test/launchers/Examples - EAP7 - helloworld-jms.launch, tests/org.jboss.tools.examples.ui.bot.test/launchers/Examples - EAP7.launch, tests/org.jboss.tools.examples.ui.bot.test/launchers/Examples - JavaEE7.launch, tests/org.jboss.tools.examples.ui.bot.test/launchers/Examples - WildFly11  - helloworld-jms.launch, tests/org.jboss.tools.examples.ui.bot.test/launchers/Examples - WildFly11.launch, tests/org.jboss.tools.examples.ui.bot.test/pom.xml, tests/org.jboss.tools.examples.ui.bot.test/resources/servers/eap-7.json, tests/org.jboss.tools.examples.ui.bot.test/resources/servers/eap-blacklist-test-errors-regexes.json, tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/AbstractImportQuickstartsTest.java, tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/EAPImportQuickstartsTest.java
- Updated to eap71
- Moved checkstyle plugin req to global build
- Ignore more documented errors
- Updated readme
Documented errors:
Checkstyle execution... - is automatically resolved, but sometimes it hangs.
spring-petclinic - relates to JS support and split JS files
jaxws-retail - missing files needs to be generated from wsdl first. 
Referenced file contains errors.. & nvalid content was found - relates to duplicate entries for xml definition files, [bz & duplicates](https://bugzilla.redhat.com/show_bug.cgi?id=1193543)
Related job [run](https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/examples.eap.it.weekly/158/)
Signed-off-by: vprusa <vprusa@redhat.com>
=> JBIDE-25520

tests/org.jboss.tools.jsf.ui.test/build.properties, tests/org.jboss.tools.jsf.ui.test/launchers/AllTestsSuite.launch, tests/org.jboss.tools.jsf.ui.test/launchers/JSFAllTestsSuite.launch, tests/org.jboss.tools.jsf.ui.test/pom.xml, tests/org.jboss.tools.jsf.ui.test/resources/requirements.json, tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/AllTestsSuite.java, tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/project/CreateJSFProjectTest.java, tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/project/ExportImportWARTest.java, tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/project/RunJSFProjectTest.java, tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/requirement/DoNotUseVPERequirement.java, tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/utils/JSFTestUtils.java
- Workaround for infinite building workspace loop
- New way of downloading jboss-eap 7.0 server, via download-maven-plugin
- Itests are green on jenkins rhel and win slaves
=> JSF itests stabilization

tests/org.jboss.tools.examples.ui.bot.test/pom.xml
Because of [https://issues.jboss.org/browse/JBIDE-25742](https://issues.jboss.org/browse/JBIDE-25742)
=> Removed jaxws-repo repository

tests/org.jboss.tools.examples.ui.bot.test/META-INF/MANIFEST.MF, tests/org.jboss.tools.examples.ui.bot.test/pom.xml, tests/org.jboss.tools.examples.ui.bot.test/resources/servers/eap-7.json, tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist-test-errors-regexes.json, tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/AbstractImportQuickstartsTest.java
Fixed some errors with Maven update call,
added as repository https://coderplus.github.io/m2e-connector-for-jaxws-maven-plugin/ because the old one had broken one of the underlying xml files,
updated versions - bundles, eap-7.x,
ignore known warning.
In progress, will add test run soon.
=> JBIDE-26291

tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/bean/template/NullValuesInjectionTemplate.java, tests/org.jboss.tools.deltaspike.ui.bot.test/pom.xml, tests/org.jboss.tools.deltaspike.ui.bot.test/resources/prj/configureProblemSeverity/pom.xml, tests/org.jboss.tools.deltaspike.ui.bot.test/resources/servers/requirements.json, tests/org.jboss.tools.deltaspike.ui.bot.test/src/org/jboss/tools/deltaspike/ui/bot/test/DeltaspikeAllBotTests.java, tests/org.jboss.tools.deltaspike.ui.bot.test/src/org/jboss/tools/deltaspike/ui/bot/test/DeltaspikeTestBase.java
- udpate cdi used in deltaspike tests
- fix cdi nullvalueInjection test
=> Update runtime servers for deltaspike to wildfly-16

plugins/org.jboss.tools.cdi.reddeer/src/org/jboss/tools/cdi/reddeer/validators/BeansXmlValidationProviderCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDI20SuiteTest.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/cdi20/BeansXMLBeansEditorTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/cdi20/BeansXMLValidationTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/validation/cdi20/BeansXMLValidationQuickFixTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/wizard/cdi11/CDIWebProjectWizardTestCDI11.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/wizard/cdi20/CDIWebProjectWizardTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/wizard/template/CDIWebProjectWizardTemplate.java
JBIDE-24963-2 - Create CDI 2.0 integration tests - step 2; following testclasses are added:
- BeansXMLBeansEditorTestCDI20.class
- BeansXMLValidationTestCDI20.class
- BeansXMLValidationQuickFixTestCDI20.class
@odockal  please review
Jira: https://issues.jboss.org/browse/JBIDE-24963
Jenkins: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cdi20.itests/16/
=> JBIDE-24963-2 - Create CDI 2.0 integration tests - step 2

tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDI20SuiteTest.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/bean/cdi20/AsYouTypeValidationTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/dialog/cdi20/AllAssignableDialogTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/dialog/cdi20/AssignableDialogFilterTestCDI20.java
**JBIDE-24963-4 - Add the following testclasses:** 
- AllAssignableDialogTestCDI20
- AssignableDialogFilterTestCDI20
- AsYouTypeValidationTestCDI20
**Jenkins**: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cdi20.itests/70/
**Jira**: https://issues.jboss.org/browse/JBIDE-24963
please review @jkopriva
=> JBIDE-24963-4 - add new testclasses for CDI 2.0

plugins/org.jboss.tools.cdi.reddeer/src/org/jboss/tools/cdi/reddeer/validators/BeansXmlUIValidationProvider.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDI20SuiteTest.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/cdi20/BeansXMLUITestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/openon/cdi20/BeansXMLOpenOnTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/template/BeansXMLUITemplate.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/validation/cdi20/BeansXMLAsYouTypeValidationTestCDI20.java
**JBIDE-24963-5 - add new testclasses for CDI 2.0:** 
- BeansXMLAsYouTypeValidationTestCDI20.class
- BeansXMLOpenOnTestCDI20.class
- BeansXMLUITestCDI20.class
**Jenkins:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cdi20.itests/98/
**Jira:** https://issues.jboss.org/browse/JBIDE-24963
=> JBIDE-24963-5 - add new testclasses for CDI 2.0

plugins/org.jboss.tools.cdi.reddeer/src/org/jboss/tools/cdi/reddeer/validators/ScopeValidationProviderCDI20.java, plugins/org.jboss.tools.cdi.reddeer/src/org/jboss/tools/cdi/reddeer/validators/StereotypeValidationProviderCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDI20SuiteTest.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/bean/cdi20/VetoedAnnotationTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/bean/template/VetoedAnnotationTemplate.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/scope/cdi20/ScopeValidationQuickFixTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/scope/template/ScopeValidationQuickFixTemplate.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/stereotype/cdi20/StereotypeValidationQuickFixTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/stereotype/template/StereotypeValidationQuickFixTemplate.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/wizard/cdi20/UtilityProjectWithCDITestCDI20.java
JBIDE-24963-9 - Add new testclasses:
- ScopeValidationQuickFixTestCDI20
- StereotypeValidationQuickFixTestCDI20
- UtilityProjectWithCDITestCDI20
- VetoedAnnotationTestCDI20
**Jenkins:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cdi20.itests/91/
**Jira:** https://issues.jboss.org/browse/JBIDE-24963
please review @odockal @jkopriva
=> JBIDE-24963-9 - add new testclasses for CDI 2.0

tests/org.jboss.tools.examples.ui.bot.test/README.md, tests/org.jboss.tools.examples.ui.bot.test/pom.xml, tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-17.json, tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist-test-errors-regexes.json
JBIDE-26558 - Update WildFly to version 17 in examples.itests.
**Jenkins:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/examples.wildfly.it.weekly/545/
**Jira:** https://issues.jboss.org/browse/JBIDE-26558
=> JBIDE-26558 - Update WildFly to version 17 in examples.itests

plugins/org.jboss.tools.cdi.reddeer/src/org/jboss/tools/cdi/reddeer/validators/BeanValidationProvider.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDI20SuiteTest.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/weld/cdi20/WeldBuiltInContextsTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/weld/cdi20/WeldExcludeTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/weld/cdi20/WeldParametersAnnotationTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/weld/cdi20/WeldScanTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/weld/template/WeldBuiltInContextsTemplate.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/weld/template/WeldExcludeTemplate.java
**JBIDE-24963-10 - Add new testclasses:**
- WeldBuiltInContextsTestCDI20
- WeldExcludeTestCDI20
- WeldParametersAnnotationTestCDI20
- WeldScanTestCDI20
**Jenkins:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cdi20.itests/107/
**Jira:** https://issues.jboss.org/browse/JBIDE-24963
=> JBIDE-24963-10 - add new testclasses for CDI 2.0

tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist-test-errors-regexes.json, tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/AbstractImportQuickstartsTest.java
JBIDE-26758 - examples.wildfly.itests contains errors like "There is no project with name " for following projects:
- dist
- wicket-ear
- helloworld-classfiletransformer
**Jenkins:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/examples.wildfly.it.weekly/592/
**Jira:** https://issues.jboss.org/browse/JBIDE-26758
please review @odockal @jkopriva 
=> JBIDE-26758 - examples.wildfly.itests contains errors like "There is no project with name ..."

plugins/org.jboss.tools.cdi.reddeer/src/org/jboss/tools/cdi/reddeer/common/model/ui/editor/EditorPartWrapper.java, tests/org.jboss.tools.cdi.bot.test/META-INF/MANIFEST.MF, tests/org.jboss.tools.cdi.bot.test/resources/trimTestsExampleFiles/ApplicationScoped.java, tests/org.jboss.tools.cdi.bot.test/resources/trimTestsExampleFiles/ConversationScoped.java, tests/org.jboss.tools.cdi.bot.test/resources/trimTestsExampleFiles/Decorator.java, tests/org.jboss.tools.cdi.bot.test/resources/trimTestsExampleFiles/DefaultTest.java, tests/org.jboss.tools.cdi.bot.test/resources/trimTestsExampleFiles/DefaultTestBean.java, tests/org.jboss.tools.cdi.bot.test/resources/trimTestsExampleFiles/Dependent.java, tests/org.jboss.tools.cdi.bot.test/resources/trimTestsExampleFiles/RequestScoped.java, tests/org.jboss.tools.cdi.bot.test/resources/trimTestsExampleFiles/SessionScoped.java, tests/org.jboss.tools.cdi.bot.test/resources/trimTestsExampleFiles/Singleton.java, tests/org.jboss.tools.cdi.bot.test/resources/trimTestsExampleFiles/TestDecorator.java, tests/org.jboss.tools.cdi.bot.test/resources/trimTestsExampleFiles/TestInterceptor.java, tests/org.jboss.tools.cdi.bot.test/resources/trimTestsExampleFiles/TestStereotype.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDI20SuiteTest.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDITestBase.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/bean/cdi20/BeanValidationQuickFixTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beans/bean/template/BeanValidationQuickFixTemplate.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/cdi20/BeansXMLDiscoveryModesTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/completion/cdi20/BeansXMLCompletionTestCDI20.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/completion/template/BeansXMLCompletionTemplate.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/beansxml/template/BeansXMLDiscoveryModesTemplate.java, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/validation/cdi20/CDIValidatorTestCDI20.java
**JBIDE-24963-3 - update CDI to 2.0; adds those classes:**
- BeanValidationQuickFixTestCDI20.class
- BeansXMLCompletionTestCDI20.class
- CDIValidatorTestCDI20.class
- BeansXMLDiscoveryModesTestCDI20.class
Jenkins: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cdi20.itests/29/
Jira: https://issues.jboss.org/browse/JBIDE-24963
=> JBIDE-24963-3 - add new testclasses for CDI 2.0

tests/org.jboss.tools.central.ui.bot.test/resources/blacklist-launcher-application-errors-regexes.json
Fix the central.itests failing due not blacklisted issue in Launcher Application project. The 
**Jenkins:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/central.itests/574/
**Jira:** https://issues.jboss.org/browse/JBIDE-26882
=> JBIDE-26882 - Fix the central.itests failing due not blacklisted issue

tests/org.jboss.tools.maven.ui.bot.test/pom.xml, tests/org.jboss.tools.maven.ui.bot.test/resources/servers/wildfly.json
JBIDE-26846 - update WildFly version to 18 in maven.itests.
Please review @jkopriva @zcervink 
**Jenkins:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/maven.itests/847/
**Jira:** https://issues.jboss.org/browse/JBIDE-26846
=> JBIDE-26846 - update WildFly version to 18 in maven.itests.

tests/org.jboss.tools.examples.ui.bot.test/pom.xml, tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist-test-errors-regexes.json, tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly.json
JBIDE-26845 - Update WildFly to version 18 in examples.wildfly.itests and check and update entries in the wildfly-blacklist and wildfly-blacklist-test-errors-regexes.json files
Please review @odockal @jkopriva 
**Jira:** https://issues.jboss.org/browse/JBIDE-26845
**Jenkins:** soon in a comment below
=> JBIDE-26845 - Update WildFly to version 18 in examples.wildfly.itests

tests/org.jboss.tools.examples.ui.bot.test/pom.xml
Set deploy on server on true as default in examples itests (in EAP, WildFly and Java EE integration tests).
**Jira:** https://issues.redhat.com/browse/JBIDE-26997
=> JBIDE-26997 - Enable deploy on server by default in all example itests (EAP, WildFly and Java EE itests)

tests/org.jboss.tools.examples.ui.bot.test/pom.xml
- pom.xml updated
- new Jenkins job created (with appropriate default parameters) - https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/examples.javaee8.it.weekly/
**Jenkins (the new job for Java EE 8):** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/examples.javaee8.it.weekly/
**JIRA:** https://issues.redhat.com/browse/JBIDE-27022
=> JBIDE-27022 - Update Java EE example.itests to use Java EE 8 repo

tests/org.jboss.tools.cdi.bot.test/pom.xml
Add missing profile for cdi 2.0 smoke suite to the pom.xml. Jenkins run includes the build and run using the newly added profile.
**Jira:** https://issues.redhat.com/browse/JBIDE-27087
**Jenkins:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cdi20.itests/490/
=> Add missing profile for cdi 2.0 smoke suite to the pom.xml

tests/org.jboss.tools.livereload.ui.bot.test/pom.xml, tests/org.jboss.tools.livereload.ui.bot.test/resources/servers/wildfly.json
Update WildFly to version 19 in livereload itests
**Jira:** https://issues.redhat.com/browse/JBIDE-27154
**Jenkins:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/DSL%20Jobs%20seed/job/Studio/job/Quality/job/Integration-tests/job/livereload-itests/17/
=> Update WildFly to version 19 in livereload itests

tests/org.jboss.tools.cdi.bot.test/pom.xml, tests/org.jboss.tools.cdi.bot.test/resources/servers/requirements.json, tests/org.jboss.tools.cdi.bot.test/src/org/jboss/tools/cdi/bot/test/CDITestBase.java
JBIDE-27118 - Update WildFly version in cdi.itests to version 19
**Jira:** https://issues.redhat.com/browse/JBIDE-27118
**Jenkins - first run - CDI 1.2 OK, CDI 2.0 blocked by JBIDE-27147:** 
https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cdi12.itests/768/
https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cdi20.itests/503/
Current state - CDI 2.0 issue (JBIDE-27147) reported and fixed in this PR. Tests passed on localhost, all Jenkins runs are blocked by mysterious Jenkins issue - JBIDE-27148.
@odockal @jkopriva I suggest resolve the mystery blocker and then rerun the tests on Jenkins. After that we can merge.
=> JBIDE-27118 - Update WildFly version in cdi.itests to version 19

tests/org.jboss.tools.maven.ui.bot.test/pom.xml, tests/org.jboss.tools.maven.ui.bot.test/resources/servers/wildfly.json, tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/project/JSFProjectTest.java, tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/project/SCMCheckoutProject.java
JBIDE-27117 - Update WildFly version in maven.itests to version 19
**JIRA:** https://issues.redhat.com/browse/JBIDE-27117
**JENKINS: (hash before rebase)** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/DSL%20Jobs%20seed/job/Studio/job/Quality/job/Integration-tests/job/maven-itests/44/
=> JBIDE-27117 - Update WildFly version in maven.itests to version 19

tests/org.jboss.tools.examples.ui.bot.test/pom.xml, tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist-test-errors-regexes.json, tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly.json, tests/org.jboss.tools.examples.ui.bot.test/src/org/jboss/tools/examples/ui/bot/test/integration/AbstractImportQuickstartsTest.java
JBIDE-27086 - Update WildFly version in examples.itests to version 19
Jenkins: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/DSL%20Jobs%20seed/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/103/
JIRA: https://issues.redhat.com/browse/JBIDE-27086
=> JBIDE-27086 - Update WildFly version in examples.itests to version 19

tests/org.jboss.tools.maven.ui.bot.test/pom.xml, tests/org.jboss.tools.maven.ui.bot.test/resources/servers/wildfly.json
**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/maven-itests/21/
**Jira:** https://issues.redhat.com/browse/JBIDE-27313
**Issues in jenkins run:**
- https://issues.redhat.com/browse/JBIDE-27348 (caused by update of WF to version 20)
- https://issues.redhat.com/browse/JBIDE-27145 (caused by testing something, that does not hase to be tested; found when updating WF to version 19)
=> JBIDE-27313 - Update WildFly version in maven.itests to version 20

tests/org.jboss.tools.maven.ui.bot.test/src/org/jboss/tools/maven/ui/bot/test/AbstractMavenSWTBotTest.java
**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/maven-itests/171/
**Jira:** https://issues.redhat.com/browse/JBIDE-27725
=> Fix the failing maven itests due to the UI changes in the Preferences dialog

.github/workflows/build_test.yml
Hi!
Following the [GH Action Security Hardening](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) guide we should use the commit SHA instead of the `branch` or `tag` for any third-party untrusted action.
This PR was submitted by a script.
=> Pin 3rd-party actions to SHA1
